### ISSUE TITLE
Support for multiple build variants

### ISSUE THREAD

**Issue by scompt** [facebook/screenshot-tests-for-android#1]
Thanks for releasing this! I've been looking forward to taking a look at it.

My app has a bunch of build types and a couple build flavors yielding lots of different build variants. When I follow the docs to add your project and run a simple test, I get the following error:

```
$ ./gradlew screenshotTests

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':ExampleCompany:pullScreenshots'.
> Task with path ':packageDebugAndroidTest' not found in project ':ExampleCompany'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.355 sec
```

It looks like the plugin is trying to find the `packageDebugAndroidTest` task, which doesn't exist in my app. Instead, I would like to use the `packagePlayInternalDebugAndroidTest` task.

Looking around in the plugin, I found [this](https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/groovy/com/facebook/testing/screenshot/build/ScreenshotsPlugin.groovy#L5), which suggests that I can configure the plugin like so:

```
screenshots {
    testApkTarget = 'packagePlayInternalDebugAndroidTest'
}
```

Even with this line, I get the same error. Any advice?

**Comment by tdrhq** [comment]
what command do you typically use to run your tests? I probably need to make this line customizable: https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/groovy/com/facebook/testing/screenshot/build/ScreenshotsPlugin.groovy#L72

**Comment by scompt** [comment]
> what command do you typically use to run your tests?

`connectedAndroidTest`

**Comment by tdrhq** [comment]
ah, looks like I have a bug in https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/groovy/com/facebook/testing/screenshot/build/ScreenshotsPlugin.groovy#L17 where I'm reading the property before you get a chance to set it which kind of defeats the purpose. Let me fix this.

**Comment by tdrhq** [comment]
I landed a fix: https://github.com/facebook/screenshot-tests-for-android/commit/7b3e997ae76459e6465c601c9653cb37a1ac63a6

Would you be able to install the jars into a local maven to test this out? If it works, I'll deploy it as a new version early next week (will try to bundle it with other bugs)

**Comment by scompt** [comment]
Yep, that fixes it for me. At least it gets me to another error. I'll take a look at that tomorrow.

**Comment by tdrhq** [comment]
Still having issues? I'm closing this task out for now, but feel free to open another one for the new issues!

**Comment by arpit130** [comment]
Please update it the plugin jar on Maven.

**Comment by tdrhq** [comment]
@arpit130, I have updated the jar on maven central and bumped the version to 0.2.2. Let me know if you find any issues
