### ISSUE TITLE
`repoClean` task dependency 

### ISSUE THREAD

**Issue by jonfinerty** [facebook/screenshot-tests-for-android#10]
Hi,

This project is a great idea and I'm looking into getting it to run on windows. At the moment I'm trying to build the source and I'm running into a problem running a simple `gradlew tasks` to get a list of available tasks. Gradle reports that `Could not determine the dependencies of task ':uploadAllLocal'`.

I've fiddled with the build.gradle and it seems that the dependsOn of `":repoClean"` for the task is causing the issue. 

I can't find any other reference to a `repoClean` task in this project, or elsewhere on the internet. Can you point me in the right direction at all?

Thanks,
Jon

**Comment by tdrhq** [comment]
Oh dang, definitely looks like a mistake. Sending out a fix now.

**Comment by tdrhq** [comment]
Fixed in https://github.com/facebook/screenshot-tests-for-android/commit/f2a8f1913e3853c6a3626e2a071f249cbaac5e82 , thanks!

This will go out as part of v0.2.4

**Comment by jonfinerty** [comment]
Thanks for the quick fix
