### ISSUE TITLE
How do I use jitpack with this project?

### ISSUE THREAD

**Issue by sridoodla** [facebook/screenshot-tests-for-android#102]
If I include only `plugin` or `core` I get an error that the other is missing. If I include both, I get the following error : 

![image](https://user-images.githubusercontent.com/3683106/28691527-2c573c3a-72d2-11e7-9a37-f14a42f51fd8.png)

My classpath dependencies : 
![image](https://user-images.githubusercontent.com/3683106/28691613-7c2f7a38-72d2-11e7-965f-1e38270d5b0b.png)

If I try to include both ( as per jitpack docs, just don't specify the sub-project ), I get the following error :
![image](https://user-images.githubusercontent.com/3683106/28691696-af59f55a-72d2-11e7-9485-c14c4fd8c387.png)

The jitpack build in question : 
https://jitpack.io/#sridoodla/screenshot-tests-for-android/8a17ff1eb5

**Comment by xiphirx** [comment]
Unsure, you would likely have more success asking in their Gitter chatroom https://gitter.im/jitpack/jitpack.io
