### ISSUE TITLE
Randomly missing backgrounds

### ISSUE THREAD

**Issue by brianguertin** [facebook/screenshot-tests-for-android#103]
So, I’m not sure what causes this because it’s random, but about 20% of the time, my screenshots come out with random chunks missing from them (see attached).

If I run the _exact_ same test again the same screenshots will usually come out correctly. I’m not doing any background processing or network requests or fancy animations; just setting content on the views in the UI  thread and then capturing the activity via `Screenshot.snapActivity`.

Anyone else seen this / any ideas? Because of the randomness, I can’t use `verifyMode` in continuous integration. If it at least broke consistently I would be happy ;)

Using: 
com.facebook.testing.screenshot:plugin:0.4.3
compileSdkVersion 25
buildToolsVersion "26.0.0"
Android emulator (Nexus 4, API 21)

Examples: Note that in the first two shots the missing chuck is actually 100% transparent; there's just a whole piece missing from the screenshot!

In this first shot, the background color comes from a single FrameLayout containing all the views on screen; with `android:background="#efeff4"` set. How is it capturing the background for most of the screen but missing such a random chunk?

![orderitem_add](https://user-images.githubusercontent.com/120002/28687399-4256278a-72dc-11e7-8916-9e9696c8581a.png)

In this second shot, the background color comes from a single FrameLayout containing all the views on screen; with `android:background="@android:color/white"` set.

![restaurant](https://user-images.githubusercontent.com/120002/28687401-43822df2-72dc-11e7-9a6f-e8436f192c9c.png)

In this last one, everyting is contained in a LinearLayout with `android:background="#efeff4"`, the chunk on the top right does have a background, but it’s the wrong color, somehow. The color that appears (seems to be `#D4D4D5`) does not exist anywhere in my project 😕 

![checkout_delivery_filledfields](https://user-images.githubusercontent.com/120002/28687432-5bc862a0-72dc-11e7-8164-197eb841c4ef.png)

(If I have some extra time I’ll try to reduce this to a single test case.)

**Comment by xiphirx** [comment]
Please open a new issue if you were able to create a reproducible test case. Thanks!

**Comment by zred77** [comment]
@brianguertin Have you found a solution? I'm facing the same issue, about 1 out of 10 screenshot has random missing chunks.
