### ISSUE TITLE
Screenshots do not show elevation

### ISSUE THREAD

**Issue by sridoodla** [facebook/screenshot-tests-for-android#104]
In material, you can specify elevation for the cards. Screenshots do not show the shadow regardless of the elevation value.

**Comment by xiphirx** [comment]
I believe this is due to the fact that shadows are drawn outside of a view's knowledge, meaning its not actually a part of the view itself.

I'll have to see if this would be possible.

**Comment by xiphirx** [comment]
This is not currently possible it seems because elevation is drawn outside of a view's control.

**Comment by winterDroid** [comment]
But even if it is outside, shouldn't it be possible to take a screenshot of the parent view then? Even then it seems not to be recorded with shadow.

**Comment by winterDroid** [comment]
I got it working in a very hacky way by using a custom `LayoutInflaterFactory` (which I use anyway to have deterministic progress bars) and setting there `Build.VERSION.SDK_INT` to 20. This leads to falling back on the compat shadows. But it would be great to get actually native support.

I also tried actually inflating a layout on an activity with a `CardView` and taking a screenshot of the whole activity. Even there it is not showing up.

**Comment by xiphirx** [comment]
What I mean by "outside of a view's control" is that elevation isn't drawn by the normal view hierarchy pass it seems. Its a completely separate thing that is innate to the composition of your screen. Capturing the parent wont do anything to help that. 

Setting the sdk version to 20 is not correct here. It may give you compat elevation but it will also make the code function like you're running API 20, which can alter the test's behavior.

**Comment by winterDroid** [comment]
I guess it is related to the different rendering layers. Probably the most accurate, and maybe the only possible, way to get the actual Screenshot is to use the MediaProjection API in 21+.

**Comment by kirillzh** [comment]
Is this still not possible to implement from technical perspective? Are there any new/changed APIs that would let us capture elevation? I understand it's out the library's control, at least last year, but it's a bit disappointing that this is not supported, curious if there's anything that we can do to capture elevations?

**Comment by xiphirx** [comment]
As long as its rendered outside of the view pipeline we can't do much. The best thing we can do is take a screenshot of the entire screen, which isn't ideal.

**Comment by SamCosta1** [comment]
Is this still the case?

**Comment by sahin-a** [comment]
2023 wants to know too if it's still the case
