### ISSUE TITLE
I want to run screenshot tests in multiple devices

### ISSUE THREAD

**Issue by josedlpozo** [facebook/screenshot-tests-for-android#112]
# I want to run screenshot tests in multiple devices

### Actual behaviour
Screenshot tests can only be run in one device. Each time the user runs the tests in recordMode, screenshot folder is cleared, so if we ran the tests in more than one device, each time this folder is overriden with the new screenshots.

### Expected behaviour
I want to be able to run screnshoot tests in multiple devices and I want to verify that the screenshot just taken is the same as the one we have taken before in the same device and not in another.

In android development a well known issue is fragmentation, we have many API versions and verify that our app is working well in each version is mandatory.

For this goal, we need:

- No clear screenshot folder. Only remove the screenshots that have been taken in the device we are running the recordMode again.
- Identify each screenshot uniquely taking in account the device.

**Comment by just-kip** [comment]
What about setting landscape mode to device?

My workaround:

I user script to create and run device before every test run 

```
$ANDROID_HOME/tools/bin/avdmanager create avd --force --name NEXUS_5X --device "Nexus 5X" --package 'system-images;android-22;google_apis;x86'
$ANDROID_HOME/emulator/mksdcard -l sdcard 100M ~/.android/avd/NEXUS_5X.avd/sdcard.img
cp -f .avd_config/nexus_5x/config.ini ~/.android/avd/NEXUS_5X.avd
cp -f .avd_config/nexus_5x/hardware-qemu.ini ~/.android/avd/NEXUS_5X.avd
```

```
$ANDROID_HOME/emulator/emulator @NEXUS_5X -sdcard ~/.android/avd/NEXUS_5X.avd/sdcard.img
```
and `config.ini` contain's  `hw.initialOrientation=landscape`

my build.gradle 
```
task updateScreenshotDirs << {
    def screenSizeOutput = new ByteArrayOutputStream()
    exec {
        commandLine 'adb', 'shell', 'wm', 'size'
        standardOutput screenSizeOutput
    }

    def densityOutput = new ByteArrayOutputStream()
    exec {
        commandLine 'adb', 'shell', 'wm', 'density'
        standardOutput densityOutput
    }

    def orientationOutput = new ByteArrayOutputStream()
    exec {
        commandLine 'adb', 'shell', 'dumpsys', '|', 'grep', /'SurfaceOrientation'/
        standardOutput orientationOutput
    }

    def screenSize = screenSizeOutput.toString().replaceFirst("\\D+", "").trim()
    def density = densityOutput.toString().replaceAll("\\D+", "").trim()

    def outputDir = project.screenshots.recordDir + "/" + "screen-" + screenSize + "-density-" + density

    project.screenshots.recordDir = outputDir
    System.out.println("New screenshot output directory: " + outputDir)
}
```

**Comment by TonyAssetmng** [comment]
adb -s {deviceid} exec-out screencap -p
