### ISSUE TITLE
Please do a Release 0.4.4

### ISSUE THREAD

**Issue by Empty2k12** [facebook/screenshot-tests-for-android#114]
`0.4.4-beta` is referenced multiple times in the project, however it cannot be found on maven.

fb229a9 fixes the Screenshot process for API 23+, which is what many people need.

**Comment by tdrhq** [comment]
will try to do an update today

**Comment by tdrhq** [comment]
done

**Comment by Empty2k12** [comment]
Thank your very much for the fast response and for maintaining this
project!
