### ISSUE TITLE
Python complains about not finding "ANDROID_SDK" or "ANDROIR_HOME" even though I have set them on my Mac

### ISSUE THREAD

**Issue by xiaogegexiao** [facebook/screenshot-tests-for-android#123]
Hi I'm using screenshot-test on my Android project and executing screenshotTests task

So the first 2 sub tasks executed well
:app:connectedDebugAndroidTest
:app:connectedAndroidTest

But when it went to 
:app:pullScreenshots

I got these error msg

> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/Users/xiaomei/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.2/eb92d3dc1fe3d794de2cc0242aabda1e17fd634e/plugin-0.4.2.jar/android_screenshot_tests/pull_screenshots.py", line 330, in <module>
>   File "/Users/xiaomei/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.2/eb92d3dc1fe3d794de2cc0242aabda1e17fd634e/plugin-0.4.2.jar/android_screenshot_tests/pull_screenshots.py", line 286, in main
>   File "/Users/xiaomei/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.2/eb92d3dc1fe3d794de2cc0242aabda1e17fd634e/plugin-0.4.2.jar/android_screenshot_tests/pull_screenshots.py", line 282, in setup_paths
>   File "/Users/xiaomei/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.2/eb92d3dc1fe3d794de2cc0242aabda1e17fd634e/plugin-0.4.2.jar/android_screenshot_tests/common.py", line 27, in get_android_sdk
> RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set

I'm wondering if there is anyone else experiencing the same issue?

I just tried on my mac terminal. I am quite sure that my ANDROID_SDK is set properly
![image](https://user-images.githubusercontent.com/2315319/31261081-e24c955a-aa9d-11e7-8909-e4633bc304c4.png)

Please let me know if I did something wrong. Any help is appreciated, Thanks

**Comment by xiphirx** [comment]
You need to make sure that the environment that the python script runs in has the environment variable set.

**Comment by xiaogegexiao** [comment]
Thanks. Yeah if I know the environment what the python scripts are running on, it would be easy. But I assume the python scripts are running on my Mac book or on some other different environment I don't know? How should I know which environment it is running on?
