### ISSUE TITLE
Document `testApkTarget`

### ISSUE THREAD

**Issue by jonfinerty** [facebook/screenshot-tests-for-android#13]
I added the plugin to my build, with the instructions found in http://facebook.github.io/screenshot-tests-for-android/#getting-started and then tried running `gradle tasks`. I got the error:

```
Execution failed for task ':tasks'.
> Could not determine the dependencies of task ':app:pullScreenshots'.
```

Through looking through the stacktrace and googling I found https://github.com/facebook/screenshot-tests-for-android/issues/1 and the fact I need to do the following to inform screenshots about the name of the test task:

```
screenshots {
    testApkTarget = 'connectedAndroidTestDebug'
}
```

Which will be different for a lot of users. It would be good if either the docs mentioned this or there was a more helpful error message when it's not configured properly.

**Comment by Kusand** [comment]
I was having similar problems, so I'm glad this issue was opened. The documentation is definitely sparse right now.

**Comment by tdrhq** [comment]
TBH, I'm not a gradle expert so I might have got this wrong.

testApkTarget should be the target that generates the APK, and connectedAndroidTestTarget should be the target that runs it. At least that's how it's meant to be, and I hope I can get rid of testApkTarget and somehow discover it from connectedAndroidTestTarget.

Can you show me a typical gradle configuration where the *default* setup won't work? I'll try to optimize the error messages for that configuration if possible.

**Comment by Kusand** [comment]
Pretty much any time that there are build flavors is the issue, I think. I can try to set up a demo on github later.

**Comment by michael-mohemian** [comment]
I have the same issue with build flavors, tried it with version 0.4.

`./gradlew screenshotTests --stacktrace"`
results in
`* Exception is:
org.gradle.api.GradleException: Could not determine the dependencies of task ':example:pullScreenshots'.`

**Comment by tdrhq** [comment]
hmm, I'm able to repro if use productFlavors {} to the example app. Looking into it, I can probably make the output better, but the workaround is to use 

``` 
  screenshots {
    testApkTarget = 'connected<Flavor>DebugAndroidTest',
  }
```

**Comment by russhwolf** [comment]
I couldn't get my tests working using `testApkTarget = 'connected<Flavor>DebugAndroidTest'`, but it did work when I switched to `testApkTarget = 'package<Flavor>DebugAndroidTest'` as was suggested [here](https://github.com/facebook/screenshot-tests-for-android/issues/50#issuecomment-263309051).

**Comment by xiphirx** [comment]
Documented in the wiki https://github.com/facebook/screenshot-tests-for-android/wiki/Gradle-Setup
