### ISSUE TITLE
FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.

### ISSUE THREAD

**Issue by vanniktech** [facebook/screenshot-tests-for-android#138]
Might be worth to change this so we'll be future proof?

**Comment by xiphirx** [comment]
What file is this showing up for? We should just switch the API.

**Comment by vanniktech** [comment]
The file wasn't mentioned in the output :/

**Comment by xiphirx** [comment]
Ah it seems like this is coming from Python. We should just move over the Python scripts over to 3 instead of 2, but that will be a larger change.

**Comment by vanniktech** [comment]
If there's already an issue for that then feel free to close this.

**Comment by xiphirx** [comment]
Yeah, python 3 will be part of the larger goals for this project in the near future.
