### ISSUE TITLE
Add tolerance level for screenshot comparison.

### ISSUE THREAD

**Issue by NikitaKozlov** [facebook/screenshot-tests-for-android#139]
After integration of screenshot tests a few months ago, it appeared that text rendering may vary a bit depend on the Android API version, emulators and even platform that runs emulators. Variation was somewhere around 50 pixels per 900x500 screenshot. So we added a tolerance level, for comparison we use ImageMagick. The code is similar to the following:

```
from wand.image import Image

# 0.1%
TOLERANCE = 0.0001

def _is_image_same(file1, file2):

    with Image(filename=file1) as im1, Image(filename=file2) as im2:
        diff = im1.compare(im2, 'mean_absolute')
        return diff[1] < TOLERANCE
```

Do you have any plans for adding similar feature?

**Comment by xiphirx** [comment]
I think we're trying to stick to fully deterministic tests here. You shouldn't be comparing screenshots across API levels / devices. Each screenshot should be compared to its previous version from the exact environment.
