### ISSUE TITLE
Jitpack fails to build v5.0

### ISSUE THREAD

**Issue by sridoodla** [facebook/screenshot-tests-for-android#147]
We don't use the gradle plugin as I've written my own comparison script for usage with Firebase Test Lab. Up until v4.4, I used Jitpack to acquire just the core module. However Jitpack fails to build v5.0 with the following error - 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/core/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':core'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0
```

Url -  https://jitpack.io/com/github/facebook/screenshot-tests-for-android/v0.5.0/build.log

Successful Build Url (v4.4) - https://jitpack.io/com/github/facebook/screenshot-tests-for-android/v0.4.4/build.log

**Comment by xiphirx** [comment]
Can you not just use the standard dependency? `implementation 'com.facebook.testing.screenshot:core:0.5.0'`

**Comment by sridoodla** [comment]
That worked. Although I do think the jitpack issue is a valid one. :)

Sometimes you get a fix in and need it before the next version is released.

**Comment by xiphirx** [comment]
The Jitpack issue is an issue with Jitpack, not the library. I'm able to build all modules just fine.
