### ISSUE TITLE
Screenshot with Status and Navigation bar

### ISSUE THREAD

**Issue by vanniktech** [facebook/screenshot-tests-for-android#148]
Is there any way to get a screenshot with Status and Navigation bar? I was hoping `snapActivity` would include this but it does not since it uses the `getDecorView()` from `Window`.

My use case is that often times Activity can go and control the navigation bar as well as the status bar by setting some color or making it translucent.

**Comment by xiphirx** [comment]
Have you tried walking up the view hierarchy until you reach the root and taking a screenshot of that?

**Comment by vanniktech** [comment]
I've tried `activity.window.decorView.parentView`.

**Comment by xiphirx** [comment]
What API? I set the status bar color and navigation bar color in the sample app, I'm able to see the colors using `snapActivity`. This is on API 23

**Comment by vanniktech** [comment]
I've tested `Screenshot.snap(activityRule.activity.window.decorView.rootView)` as well as `Screenshot.snapActivity(activityRule.activity)` on a Nexus 4 API 23 simulator and I do not see them in the screenshots.

Previously I was using my Pixel API 27.

The project where I'm playing around with this is actually open source - https://github.com/vanniktech/junit-rules/pull/26
The file is [here](https://github.com/vanniktech/junit-rules/pull/26/files#diff-2e6fca198df1a5d5b88fb3ae23c60204) and you can just let it run with `./gradlew recordMode screenshotTests`.

**Comment by xiphirx** [comment]
Do you mean taking a screenshot of the actual icons in the status bar / navigation bar? If so, I'm not sure that a normal application can do that since those are system views.

If you mean just colors, those are captured correctly. Your activity isn't stating that it draw's its own system bar backgrounds since its a plain `Activity`, so you dont see the status or navigation bars captured. To see them captured, you need to modify your code like this:
```diff
diff --git a/junit4-android-integration-rules/src/androidTest/java/com/vanniktech/junit4androidintegrationrules/NoOpActivity.kt b/junit4-android-integration-rules/src/androidTest/java/com/vanniktech/junit4androidintegrationrules/NoOpActivity.kt
index c75e3bd..abaa375 100644
--- a/junit4-android-integration-rules/src/androidTest/java/com/vanniktech/junit4androidintegrationrules/NoOpActivity.kt
+++ b/junit4-android-integration-rules/src/androidTest/java/com/vanniktech/junit4androidintegrationrules/NoOpActivity.kt
@@ -1,5 +1,17 @@
 package com.vanniktech.junit4androidintegrationrules

 import android.app.Activity
+import android.graphics.Color
+import android.os.Bundle
+import android.view.WindowManager

-class NoOpActivity : Activity()
+class NoOpActivity : Activity() {
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
+    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
+    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS)
+    window.navigationBarColor = Color.RED
+    window.statusBarColor = Color.GREEN
+  }
+}
```

Which results in 
![image](https://user-images.githubusercontent.com/993832/35824946-4ed7cd54-0a69-11e8-82cb-aa3596877ce3.png)

**Comment by vanniktech** [comment]
Huh interesting this does work quite indeed. Although I'm not planning on doing anything with the activity here in this project. With the uidemo I'm overriding the clock and other properties that will be reflected in the status bar. I'm however not able to get those into the screenshot. Might be that those are at a higher level.

I'll close this then and see whether I can dig up anything. Thanks for the help.

**Comment by xiphirx** [comment]
Yeah, I'm not sure if you can get those to show up in any screenshot initiated by your application. I would think those are protected by the system.
