### ISSUE TITLE
Handling aliasing on different devices

### ISSUE THREAD

**Issue by sridoodla** [facebook/screenshot-tests-for-android#151]
I'm running my tests on Firebase Test Lab and ocassionally, there are minor differences between images. This is due to aliasing and so, the borders around text, or certain images is a little fuzzed. Unfortunately, this causes our tests to fail and we have to re-run.

Do you have any strategies/solutions to help handle this?

**Comment by xiphirx** [comment]
Your test should be deterministic, and for that to happen you need to ensure the exact device / configuration is utilized. You also need to make sure that animations are turned off / their scale is set to 0.

**Comment by sridoodla** [comment]
It's the same device config ( Nexus 6P, API 27 or Pixel API 26 ). Just aliasing differs sometimes. It's running on Firebase Test Lab, so I don't have control over which particular machine spins up the VM or which device runs the screenshot tests.

![image](https://user-images.githubusercontent.com/3683106/35948144-00cdfbd4-0c20-11e8-83f5-638bacd20e61.png)

Similar to the above image.

**Comment by xiphirx** [comment]
If you're using the exact same device configuration, then the difference in aliasing is likely due to non deterministic code you have. There shouldn't be a difference between running the same screenshot test on the same device.

If you can't guarantee the device configuration, then you have issues determining whether or not small differences are caused by your code or by the difference of device configuration. To that end, I don't think it would make sense to have pixel difference tolerance be a part of the plugin portion of the library since it begs the question "what is tolerable", and I don't think theres a general answer to that nor should it be utilized for something that should be deterministic.

**Comment by sridoodla** [comment]
Before Image

![image](https://user-images.githubusercontent.com/3683106/35948513-a9a43c22-0c21-11e8-8f95-32eee8cad3e4.png)

After Image:

![image](https://user-images.githubusercontent.com/3683106/35948524-c03030a4-0c21-11e8-8c82-b285e8a584c3.png)

Difference :

![image](https://user-images.githubusercontent.com/3683106/35948708-bf0dffde-0c22-11e8-84e2-f93dcace2e5f.png)


I'm not asking for tolerance to be made part of the library.

**Comment by xiphirx** [comment]
Are you scaling that image down / up? Are you positioning it yourself?

**Comment by sridoodla** [comment]
I'm not modifying the image. What do you mean, positioning it myself?

**Comment by xiphirx** [comment]
The view you're taking a screenshot of, how is that image rendered? Is it rendered in a plain ImageView that has the size set appropriately? How is it positioned? is it positioned via its ViewGroup or something else?

**Comment by xiphirx** [comment]
If your `LinearLayout` isn't doing something weird, then I'm not sure why the output would be different. You're not recording on one API and testing on another are you? 

To see if this is an issue with your code, you can try to setup a stress test where you run the same test a bunch to see if any are different. If its consistent throughout the stress test, then you have some configuration issue.

**Comment by sridhar-vadlamani-ck** [comment]
@xiphirx So I've tested this a bunch and I'm still not sure why it happens or when.

Our screenshot tests run on Firebase Test Lab, so I don't actually have any control over what emulator runs my tests and generates screenshots.

I thought it was something to do with running screenshot tests on the UI thread vs the test thread, but after converting some tests to run on the test thread, I see the same issues with aliasing as before. Again, this is completely random and only happens sometimes.

If there was something going on in my code/layout, I'm sure it wouldn't be as random, or as insignificant as the change in the image above.

Any ideas?

It might not help, but here's part of my code anyway - 

Test Class
```kotlin
@Test
    fun captureAccountsViewRecyclerView() {
        val container = FrameLayout(targetContext)
        AppRdvs.TRANSACTIONS.setDebugOverrideForTests(false)
        RibbonFeatureHelper.forceLegacy()
        val accountsViewApiModel = createAccountsViewApiModelFromJson()
        val tipsApiModel = createTipsApiModelFromJson()
        val viewModel = AccountBureauViewModel(container, accountsViewApiModel, tipsApiModel)
        viewModel.getView().screenshotWithName(
                "screenshot"
        )
    }
```

Base Class -
```kotlin
    fun View.screenshotWithName(screenshotName: String, allowedDiffHash: String? = null) {
        val displaySize = Point()
        val windowManager = targetContext.getSystemService(Context.WINDOW_SERVICE) as WindowManager
        windowManager.defaultDisplay.getSize(displaySize)

        if (Looper.myLooper() == null) {
            Looper.prepare()
        }

        ViewHelpers.setupView(this).setExactWidthPx(displaySize.x).layout()

        val delimiter = "*"
        val screenshotNameWithAllowedDiffHash = if (allowedDiffHash == null) screenshotName else "$screenshotName$delimiter$allowedDiffHash"

        // Bitmap operations are slow, and we don't care if they're run on this thread, nor do we care about any other
        // threading issues here.
        StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder().permitAll().build())
        Screenshot.snap(this).setName(screenshotNameWithAllowedDiffHash).record()
    }
```

**Comment by xiphirx** [comment]
Are you seeing these flaky results locally as well or is it just from Firebase?

**Comment by sridhar-vadlamani-ck** [comment]
It's Firebase. But I doubt I would notice anything running locally. I only run it on one emulator. Whereas firebase probably spins up thousands of emulators on hundreds of machines. Who knows which machine my tests run on.

**Comment by xiphirx** [comment]
You need to ensure that screenshot tests are run on the exact same configuration, otherwise you will get flaky results like this. If you ensure the exact same configuration, then you will not have these issues.

**Comment by sridoodla** [comment]
When you say configuration, what do you mean exactly?

**Comment by xiphirx** [comment]
By configuration I mean OS, API level, screen resolution, density, and orientation. We have single emulator config that we run screenshot tests on.

**Comment by sridhar-vadlamani-ck** [comment]
My tests also run on a single config. Nexus 6P API 27. Vertical orientation. The screenshots I linked above are both on the same configuration, if not the exact same emulator. Aliasing differences are showing up between different emulator instances with the exact same configuration.

**Comment by sridhar-vadlamani-ck** [comment]
Also, it doesn't happen always, but frequently enough, that it's a pretty frustrating issue for our team.

**Comment by xiphirx** [comment]
Are you sure there are no animations or other things that are going on here? We dont encounter aliasing issues using this framework. 

Did you try my idea of stress testing the screenshot test? Running it 100+ times in succession to detect if it is flaky?

**Comment by sridhar-vadlamani-ck** [comment]
I'll do the stress test on my local emulator in a bit. I assume that will weed out any issues in the code itself if it produces a different screenshot.

**Comment by Laimiux** [comment]
Any update on this? Facing a similar issue myself.

**Comment by doodla** [comment]
I handled the issue by not doing pixel to pixel comparisons. I now use https://github.com/yahoo/blink-diff to compare the screenshots. We haven't had any aliasing issues since as the library takes that into account.

There's a possibility that very small changes might've been missed, but we haven't found any such behavior yet.
