### ISSUE TITLE
Allow specyfiing own Dexmaker

### ISSUE THREAD

**Issue by bakua** [facebook/screenshot-tests-for-android#152]
Hello,

I am already using [LinkedIn's dexmaker](https://github.com/linkedin/dexmaker) in my project. Since your library already bundles dexmaker with it, I end up with following error.

```
com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/android/dx/Comparison$4;
```
At the same time, I cannot exclude LinkedIn's dexmaker because crittercism's one doesn't work properly in my case. Also, it is old and unmaintained dependency anyways.

I don't see a way how to work around this one since screenshot-tests is a plugin and I cannot easily exclude its dependencies.

Could you make it a way so developers can specify own dexmaker as needed? Thanks :)

**Comment by xiphirx** [comment]
It seems like the core dependency only uses dexmaker for one thing... I can investigate whether or not its actually needed. At the very least, I can switch over to using linkedin's dexmaker.
