### ISSUE TITLE
Screenshot.snapActivity generate images too big

### ISSUE THREAD

**Issue by omainegra** [facebook/screenshot-tests-for-android#158]
I'm testing with a real device *Nexus 6P*, and `Screenshot.snapActivity` generates images about 5MB. Would it be possible to somehow reduce the size of the images, taking into account that they should be versioned?. Thanks in advance.

**Comment by xiphirx** [comment]
No, sorry. This is not what you want to do anyway. Scaling your images will remove the ability to detect the smaller changes, like pixel level differences.

**Comment by smartyworld** [comment]
Might be handy now, Facebook not allow uploaded pictures over 4MB.
![Screenshot_20201216-102713](https://user-images.githubusercontent.com/10325525/102285011-71f6c800-3f89-11eb-8ddd-9229149cf6b9.png)
