### ISSUE TITLE
When running on an api 23 emulator and targeting api 23, permissions are not granted

### ISSUE THREAD

**Issue by josephmbeveridge** [facebook/screenshot-tests-for-android#16]
Since `write_external_storage` is required, if an app compiles and targets api 23 it needs to accept the external storage permission. This can be done by installing with -g, however the screenshot tests don't do this so writing to external storage always fails.

Compiling against 23 and targeting 22 does not exhibit these symptoms as it automatically grants all requested permissions.

**Comment by boourns** [comment]
just fixing the error message in this case to not suggest WRITE_EXTERNAL_STORAGE is missing would help people not get stuck

**Comment by tdrhq** [comment]
hmm, I admit I haven't been testing this on M devices. 

Since the installation happens with gradle and using Android's gradle set up, don't they already set up the permissions correctly for typical instrumentation tests?

**Comment by tdrhq** [comment]
@boourns  what would the ideal message here be to make it more parseable?

**Comment by boourns** [comment]
This URL is an example of maybe the same bug that is being hit here.  The workaround suggested (killing the app) I don't think would work with tests.

http://stackoverflow.com/questions/33062006/cant-write-to-external-storage-unless-app-is-restarted-after-granting-permissio

@josephmbeveridge could this gradle plugin be changed to install the apk using -g?  Would that resolve the issue?

@tdrhq If you wanted to be clever, determine if the app has been built against 23 and is running on 23 to emit an error specifically about this issue, but alternately just mentioning this in a longer error message would be less misleading for people who hit this case.  I myself spent a day banging my head against the wall trying to figure it out :)

**Comment by josephmbeveridge** [comment]
@boourns @tdrhq Yes, changing the plugin to install the apk using -g should fix the permissions issues on api 23 emulators.

**Comment by tdrhq** [comment]
@boourns Regarding installing with -g, the installation happens from the Android gradle plugin, so I'm surprised they don't already handle this. I imagine this is an issue with all kinds of instrumentation tests.

**Comment by tdrhq** [comment]
@boourns I'm closing this task since it should be part of the Android Gradle plugin, let me know if there's something actionable on my part. Thanks for the report!

**Comment by jimgoog** [comment]
To be clear: After PR #29 got merged, setting the compile target to API22 is not sufficient.  Your emulator must also be using API level 22 or lower.

@tdrhq Do you know if this was ever fixed in later versions of the Android Gradle Plugin?  If it was not fixed, can you file a bug on AndroidStudio and link to the bug from here?
