### ISSUE TITLE
Include Language in device unique identifier

### ISSUE THREAD

**Issue by omainegra** [facebook/screenshot-tests-for-android#163]
When testing with multiple locales, It would be great if I can test on the same device, but right now the unique identifier doesn't include the language, so the second time I run the test it would fail. Any thoughts on this??

**Comment by xiphirx** [comment]
How are you changing the language between test runs?

**Comment by omainegra** [comment]
I just change it in the System Preferences, but it could be more sophisticated like [test-butler](https://github.com/linkedin/test-butler).

**Comment by josedlpozo** [comment]
Hi @omainegra @xiphirx,

Last week I had to deal with the same problem. I fix it just adding language to device unique identifier using multipleDevices feature. Could you review it? https://github.com/facebook/screenshot-tests-for-android/pull/174

Thanks!
