### ISSUE TITLE
View bounds not updated after text changed in onAttachedToWindow()

### ISSUE THREAD

**Issue by Egorand** [facebook/screenshot-tests-for-android#164]
I've got a custom view, which is a `FrameLayout` containing a single `TextView` that is centered in parent and has its width set to `wrap_content`. Inside the custom view, I set text to `"onF"` in `onFinishInflate()`, and then update it to `"onAttachedToWindow()"` in `onAttachedToWindow()`:

```
class MyTestView(
  context: Context,
  attrs: AttributeSet
) : FrameLayout(context, attrs) {
  private lateinit var textView: TextView

  init {
    View.inflate(context, R.layout.my_test_view, this)
  }

  override fun onFinishInflate() {
    super.onFinishInflate()
    textView = findViewById(R.id.text_view)
    textView.text = "onF"
  }

  override fun onAttachedToWindow() {
    super.onAttachedToWindow()
    textView.text = "onAttachedToWindow()"
  }
}
``` 

Here's my test code:

```
@Test fun screenshotTest() {
  val view = LayoutInflater.from(InstrumentationRegistry.getTargetContext())
      .inflate(R.layout.test_layout, null)

  ViewHelpers.setupView(view)
      .setExactWidthPx(1080)
      .setExactHeightPx(1920)
      .layout()

  Screenshot.snap(view)
      .record()
}
```

The screenshot that I get has the text set to `"on"` instead of `"onAttachedToWindow()"`, which suggests that the view doesn't get remeasured between `onAttachedToWindow()` and when the screenshot is being taken.

**Comment by xiphirx** [comment]
Yeah this is a symptom of the attachment being performed within the `.record()` invocation and the framework not knowing of layout requests... 

To work around this for the time being, you should be able to attach the view in your test code when you want to, and re-layout as needed:

```
@Test fun screenshotTest() {
  val view = LayoutInflater.from(InstrumentationRegistry.getTargetContext())
      .inflate(R.layout.test_layout, null)

  ViewHelpers.setupView(view)
      .setExactWidthPx(1080)
      .setExactHeightPx(1920)
      .layout()
  
  // Manual re-layout
  val detacher = WindowAttachment.dispatchAttach(view)
  ViewHelpers.setupView(view)
      .setExactWidthPx(1080)
      .setExactHeightPx(1920)
      .layout()

  Screenshot.snap(view)
      .record()
  detacher.detach()
}
```

**Comment by xiphirx** [comment]
@Egorand did that workaround work for you?

**Comment by xiphirx** [comment]
Closing. If it becomes a larger issue feel free to open a new issue.
