### ISSUE TITLE
Could not set unknown property 'referenceDir'

### ISSUE THREAD

**Issue by sivze** [facebook/screenshot-tests-for-android#166]
cannot set custom directory for screenshots, i get the following error,
"Could not set unknown property 'referenceDir' for object of type com.facebook.testing.screenshot.build.ScreenshotsPluginExtension."

`screenshots {
    referenceDir = "$projectDir/build/reports/screenshots"
    targetPackage = "com.x.x"
}`

**Comment by xiphirx** [comment]
Hmm seems like these two features fell through the cracks during the rewrite...

**Comment by tyronen** [comment]
Hi @xiphirx, this has been an issue at my company too. We tried going back to v0.6.0, but it's quite different from the docs on github.io. Also, it doesn't quite support the workflow we want.

We use CircleCI, but it doesn't support instrumentation tests. So we upload the apks to Google's [Firebase Test Lab](https://circleci.com/docs/2.0/language-android/#testing-with-firebase-test-lab). 

We want to be able to do something like this from CircleCI:

```
./gradlew assembleDebug assembleDebugAndroidTest

## Run the test in Google's cloud
gcloud firebase android test \
  --test my/test.apk \
  --app my/app.apk \
  --results-bucket my-bucket \
  --results-dir my-dir...

# Copy the screenshots back to CircleCI
gsutil cp -R gs://my-bucket/my-dir ./my/local/dir

# referenceDir points to ./my/local/dir
./gradlew verifyDebugAndroidTestScreenshotTest
```

I'm guessing that this workflow is roughly comparable to what Facebook does internally with Buck and Sandcastle (I used to work there; knew @tdrhq).

Right now, this isn't doable; not only is `referenceDir` unsupported, but the `verify` runs the instrumentation tests locally.

I may be able to come up with a PR to remedy this. It seems doable entirely inside the plugin; if `referenceDir` is specified, pass it as `--temp-dir` to the Python script, and also skip the dependency on `connectedInstrumentTest`. 

Would that be ok? Or should there be a separate task, called `verifyOnly` or `verifyReference`?

**Comment by xiphirx** [comment]
Yes a PR to fix the referenceDir issue would be highly appreciated. I have been way too busy to look into these issues and I'm sorry that its taking so long. 

The idea of the verification command is to run the tests and compare the output against a previously recorded set of images. From what you're describing, its not entirely clear what you're verifying against. From the script you posted, you're pulling images for the current run and storing them in `./my/local/dir`, then you would like to run verify, but you just ran the tests, so this would always pass. 

Is there a point where you record a static set of images to verify against? Is it possible to run the verify task with the firebase test device?

**Comment by tdrhq** [comment]
@tyronen :wave:

**Comment by tyronen** [comment]
@xiphirx yes what we would do is do a record run and store the screenshots in our own repo. Then our CI would verify against those images. 

The verify task is built on top of the Android plugin, which is using adb to do a standard instrumentation test run. To use Firebase, we'd have to write a new Gradle task that calls gcloud instead of adb. There are a couple open-source attempts to do that, but it's considerably more complex that what I have in mind. Let me try to send you the PR in the next few days.
