### ISSUE TITLE
IllegalStateException: View too large: (1440, 7454)

### ISSUE THREAD

**Issue by scottkennedy** [facebook/screenshot-tests-for-android#168]
This needs to be configurable.  We have various large views that we want to take screenshots of, and the 1 million pixel limitation is already causing us issues.

**Comment by scottkennedy** [comment]
I'm not sure where it could go.  We don't use the Gradle plugin, just the core library.

**Comment by xiphirx** [comment]
If thats the case, then it is likely worth putting it on `Screenshot`, like

```
Screenshot.snap(view, /* pixel limit, <= 0 for no limit */)
```

**Comment by scottkennedy** [comment]
Yes, I think that would work quite well.
