### ISSUE TITLE
Fix error messages when used with flavors

### ISSUE THREAD

**Issue by Kusand** [facebook/screenshot-tests-for-android#17]
In trying to run `gradle screenshotTests` I encountered the following issue:

`Expected task ':your-app:connectedFlavor1Flavor2DebugAndroidTest' output files to contain exactly one file, however, it contains no files.`

I did the screenshots testApkTarget setup; not sure if I'm pointing it at the wrong thing, or if there's something else I'm doing wrong.

**Comment by tdrhq** [comment]
(I should preface this by saying that while I wrote all the gradle scripts here, I'm by no means a gradle expert so I might be wrong about what I'm going to say, but here goes:)

you need to set up both testApkTarget and connectedAndroidTestTarget. The first is the one that generates the APK, the second is the one that runs the tests on the devies. So it looks like the flavored target you listed should actually be the connectedAndroidTestTarget configuration.

In theory I should be able to figure out the testApkTarget from connectedAndroidTestTarget and simplify the configuration. I'll see if I can make that work somehow, but in the meantime can you try my suggestion and see if this works?

**Comment by Kusand** [comment]
Got it now. I'd update your documentation to reflect that testApkTarget
needs to be "package<RelevantThing>" and the connectedAndroidTestTarget
needs to be "connected<RelevantThing>". I'm pretty sure this is only needed
because I'm using flavors. Having it automatically respect flavors would
also be nice.

**Comment by gpeal** [comment]
I also had to do this and it resolved my issue. Documentation around this would be incredibly helpful!

**Comment by Kusand** [comment]
I've added documentation in [The Gradle Setup wiki page](https://github.com/facebook/screenshot-tests-for-android/wiki/Gradle-Setup), in the hopes of helping others.

**Comment by kylannjohnson** [comment]
I needed to do this

```
// This task reports the location of the Test APK generated by the build for use by Facebook Screenshot Tests
task packageDebugAndroidTest(dependsOn: 'assembleDebugTest') {
  outputs.dir file("${buildDir}/outputs/apk").listFiles().findAll {it.name.contains('androidTest-unaligned')}
}
```

**Comment by athkalia** [comment]
Having a similar problem related to flavors.
I am getting a 
after the usual

```
gradlew :<mylibraryname>:screenshotTests
```

(note that this is a library project and 'mylibraryname' is just a dummy name)
I am getting a:

```
> Task with path 'packageDebugAndroidTest' not found in project ':<mylibraryname>'.
```
Instead there is a 'packageProductionDebugAndroidTest' where 'Production' is a flavor.

**Comment by SergeyShustikov** [comment]
I faced with the same problem.

**Comment by xiphirx** [comment]
The rewrite generates tasks per flavor.
