### ISSUE TITLE
0.7.0 recordDir property seems to do nothing

### ISSUE THREAD

**Issue by rm8x** [facebook/screenshot-tests-for-android#171]
Plugin ignores the value and saves to some garbage location.

`Open the following url in a browser to view the results: 
  file:///var/folders/nt/bss2w1g559zf_gy45m8hgtjr0000gp/T/screenshotsOOzlo9/index.html`

**Comment by rm8x** [comment]
Yes, I am using the gradle task created for the build flavor as part of a command to run only appropriate tests. 

`./gradlew ... myTask ... recordFlavor_stagingDebugAndroidTestScreenshotTest  -Pandroid.testInstrumentationRunnerArguments.class=com.mything.SpecificTest`

**Comment by xiphirx** [comment]
This has been fixed in 0.10.0
