### ISSUE TITLE
Screenshot test pulls only last test screenshot

### ISSUE THREAD

**Issue by pranayairan** [facebook/screenshot-tests-for-android#172]
We are using screenshot test to test various **Activities** for a flow in our app. We have written 4-5 different test and each test opens up the app, go to specific activity inside the app and then take a screenshot. 

All the test pass when I run them, but in the end, **only 1 screenshot is pulled**. This screenshot is the last test screenshot. Say I have Test 1 and Test 2 both test goes to a different activity in my app after a successful run only Test 2 screenshot will be there in the result. 

If I debug the test and open the device SD card/screenshot folder, I can see screenshot after each test correctly. But for next test run, the previous run screenshots are cleared. (I can see them removed from the folder) is this correct behavior? 

Is it possible to do what We are trying to do with the library? Idea is to have various screenshots of each screen in our app (filled/unfilled) with various states and then compare it with each run. 

I tried with 0.6.0 and 0.7.0 both.

**Comment by xiphirx** [comment]
Was found to be because the Android Test Orchestrator is utilized, which seemingly runs tests in separate processes, so we lose the `ScreenshotImpl` singleton, causing it to think it needs to clear out the last test run's output.

**Comment by pranayairan** [comment]
With @xiphirx help, I was able to find the issue. If you are using `ANDROID_TEST_ORCHESTRATOR` for your test each test runs in a separate process, due to that test states are not shared. 

Screenshot test creates a singleton instance https://github.com/facebook/screenshot-tests-for-android/blob/master/core/src/main/java/com/facebook/testing/screenshot/internal/ScreenshotImpl.java#L67 this instance calls `album.cleanup();` which clears the screenshots. 

Since Test Orchestrator prevents state sharing singleton state is lost, due to this for each test before a screenshot is recorded the folder is cleared. In the end, you are left with only last run test screenshot. 

There are multiple ways to fix this

- The most ideal fix is to remove the logic of clearing the folder to **Plugin**  after screenshots are pulled from the directory. This will take more time to implement but would be ideal. 
- Another way is to not use **ANDROID_TEST_ORCHESTRATOR** but that will make your other test flaky
- An intermediate solution untill the longer fix is to disable **ANDROID_TEST_ORCHESTRATOR** only for Screenshot test. This is what we are doing, here is how you can do that 

   - Define a **project variables** inside the build.gradle project related file. You can name it "orchestrator" or anything of your choice 
`if (!hasProperty('orchestrator')) {
    ext.orchestrator = true
} else {
    ext.orchestrator = project.property('orchestrator')
}`
   
  - Use the new variable as if else condition in your **testOptions** where you define ANDROID_TEST_ORCHESTRATOR like this 
`if (project.ext.orchestrator == true) {
            execution 'ANDROID_TEST_ORCHESTRATOR'
        }`
  - By default **ANDROID_TEST_ORCHESTRATOR** is enabled for all test, however when you run the screenshot test you can use `./gradlew recordDebugAndroidTestScreenshotTest -Porchestrator=false` to run screenshot recording without orchestrator.

**Comment by eliddell1** [comment]
@pranayairan I tried your third approach above but when i record a single test it is still deleting other screenshots locally.. can you help
