### ISSUE TITLE
Single Test

### ISSUE THREAD

**Issue by timrijckaert** [facebook/screenshot-tests-for-android#175]
Is it possible to isolate one test 'screenshot' class?

**Comment by xiphirx** [comment]
Do you mean run one specific test class? You should be able to pass in the same arguments to gradle as usual with `--tests *.MyTestClass`

**Comment by timrijckaert** [comment]
I want to only run one screenshot UI Test, that will only generate a report for this test class.
I have hundreds of UI tests and it seems like having one failing test that it does not seem to trigger the task. Let alone running hundred of UI Tests takes way too long to see the end HTML report. 

Something along the lines of:

```
./gradlew verifyXXXXXXAndroidTestScreenshotTest --tests *.MyCustomViewTest
```

What do you think?

**Comment by xiphirx** [comment]
Does passing in `--tests` not do what you expect?

**Comment by timrijckaert** [comment]
Nope I immediately get this:

```
* What went wrong:
Problem configuring task :app:recordDebugAndroidTestScreenshotTest from command line.
> Unknown command-line option '--tests'.

BUILD FAILED in 1s
```

**Comment by xiphirx** [comment]
Hmm ok. I'll have to take a look into why that doesnt work.

**Comment by NikitaKozlov** [comment]
That doesn't work because `connectedAndroidTest` doesn't support `--test`. But it does support this: `-Pandroid.testInstrumentationRunnerArguments.class=<package>.MyCustomViewTest`, you can also add `#<methodName>` to run specific test from class.

**Comment by winterDroid** [comment]
Here you can find more details about the available arguments: https://github.com/googlesamples/android-testing-templates/blob/master/AndroidTestingBlueprint/README.md#custom-gradle-command-line-arguments

**Comment by xiphirx** [comment]
Yup, I remembered there being a way. Thanks for posting! You should use that to single out your test.
