### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by timrijckaert** [facebook/screenshot-tests-for-android#176]
Hiya,

It seems like the documentation is a bit out of date. 
[official docs](http://facebook.github.io/screenshot-tests-for-android/#getting-started) still state `0.6.0` as the latest version while `0.7.0` has been out for a while. 
Furthermore I can't seem to find a lot of documentation about the options for the Gradle plugin.

Thanks in advance.

**Comment by xiphirx** [comment]
I've made quite a few updates to the website recently, and it should be up to date now. http://facebook.github.io/screenshot-tests-for-android/
