### ISSUE TITLE
Enable testing on multiple devices

### ISSUE THREAD

**Issue by gpeal** [facebook/screenshot-tests-for-android#19]
First of all, this library is amazing. I've been playing around with it at Airbnb and I think it could be of huge value to us.

However, I think it would be n times more useful if we could have all of the screenshot tests run on multiple versions of Android as well as with multiple device configurations.

Setting the width to tablet width doesn't help because it doesn't use the tablet resource qualifiers when inflating views and getting other resources.

**Comment by tdrhq** [comment]
We're trying to figure out the best way to do this internally too. In a record-verify style environment, multiple devices can have a lot of extra load on developers to keep the screenshots in sync. (Not so much of an issue with automatic recording on the server which we do internally at Facebook but haven't realeased the tooling for yet.)

In the meantime, it's possible to simulate some parts of a tablet configuration in a non-tablet run using this method: http://developer.android.com/reference/android/content/res/Resources.html#updateConfiguration(android.content.res.Configuration, android.util.DisplayMetrics)

We don't really use this for this purpose, although we do use this for switching Locales within a single test run, so I do know this is pretty powerful. Just make sure to clean up any configuration in your tearDown because it sets things globally as opposed to just the current Context.

Let me know if this helps, and I'll update this task once I have a better story for multiple devices.

**Comment by gpeal** [comment]
I've gotten this sort of working by creating these helper methods:
```
    public void setConfigurationToNexus5() {
        hasSetConfiguration = true;
        Configuration config = getActivity().getResources().getConfiguration();
        DisplayMetrics dm = getActivity().getResources().getDisplayMetrics();
        dm.widthPixels = 1080;
        dm.heightPixels = 1920;
        dm.density = 3f;
        dm.scaledDensity = 3f;
        dm.densityDpi = 480;
        dm.xdpi = 480;
        dm.ydpi = 480;
        setNoncompatSizeFields(dm);
        config.orientation = Configuration.ORIENTATION_PORTRAIT;
        config.densityDpi = 480;
        config.screenWidthDp = 360;
        config.screenHeightDp = 567;
        config.smallestScreenWidthDp = 360;
        config.screenLayout = 268435538;

        getActivity().getResources().updateConfiguration(config, dm);
    }

    public void setConfigurationToNexus9() {

        hasSetConfiguration = true;
        Resources res = getActivity().getResources();
        Configuration config = res.getConfiguration();
        DisplayMetrics dm = res.getDisplayMetrics();
        dm.widthPixels = 2048;
        dm.heightPixels = 1440;
        dm.density = 2f;
        dm.scaledDensity = 2f;
        dm.densityDpi = 320;
        dm.xdpi = 320;
        dm.ydpi = 320;
        setNoncompatSizeFields(dm);
        config.orientation = Configuration.ORIENTATION_PORTRAIT;
        config.densityDpi = 320;
        config.screenWidthDp = 1024;
        config.screenHeightDp = 695;
        config.smallestScreenWidthDp = 768;
        config.screenLayout = 268435540;
        res.updateConfiguration(config, dm);
    }

    public void setConfigurationToNexus9Landscape() {
        setConfigurationToNexus9();
        Resources res = getActivity().getResources();
        Configuration config = res.getConfiguration();
        config.orientation = Configuration.ORIENTATION_LANDSCAPE;
        res.updateConfiguration(config, res.getDisplayMetrics());
    }
```

However, it seems like some things like bitmaps and drawables are cached by the asset manager so there are slight differences when running on different devices and what these test renders vs their respective devices.

**Comment by tdrhq** [comment]
Do you know where/what these caches are in AssetManager? I'm sure it should be technically possible to invalidate those caches with the hammer of reflection

**Comment by phil-lopreiato** [comment]
I've gotten testing with multiple devices to work with some gradle hacks. I modified [`recordDir`](https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/groovy/com/facebook/testing/screenshot/build/ScreenshotsPlugin.groovy#L9) to have a suffix specific to the current device attached in adb (device codename + API version), that way recorded screenshots from different devices won't conflict with each other. It's pretty hacky and basic, but is decent enough for my use.

```groovy
project.afterEvaluate {
    def pullScreenshots = project.tasks.getByName("pullScreenshots")
    pullScreenshots.dependsOn updateScreenshotDirs
}

task updateScreenshotDirs << {
    def codeNameOut = new ByteArrayOutputStream()
    exec {
        commandLine 'adb', 'shell', 'getprop', 'ro.product.name'
        standardOutput codeNameOut
    }

    def sdkOut = new ByteArrayOutputStream()
    exec {
        commandLine 'adb', 'shell', 'getprop', 'ro.build.version.sdk'
        standardOutput sdkOut
    }
    def deviceName = codeNameOut.toString().trim()
    def deviceSdk = sdkOut.toString().trim()
    def outputDir = project.screenshots.recordDir + "/" + deviceName + "_api" + deviceSdk
    project.screenshots.recordDir = outputDir
    System.out.println("New screenshot output dierctory: " + outputDir)
}
```

**Comment by xiphirx** [comment]
Merging into a more up-to-date issue #112
