### ISSUE TITLE
"verify" task is searching for a device-specific folder, even without "multipleDevices" flag

### ISSUE THREAD

**Issue by Egorand** [facebook/screenshot-tests-for-android#190]
According to the docs:

> When recording screenshots for later verification, the screenshots are not strictly tied to a specific device by default. If you wish to record screenshots for multiple device configurations and verify each independently, then you should enable multipleDevices in your screenshots block:
>
> screenshots {
  // ...
  multipleDevices true
}

The app doesn't use the flag and has a bunch of screenshots in app/screenshots. Running:

```
./gradlew :app:verifyInternalDebugAndroidTestScreenshotTest
```

Fails with:

```
IOError: [Errno 2] No such file or directory: 'screenshots/API_24_GP_XXXHDPI_1440x2560_x86_/HomeView-normal-SAMSUNG_S8|DEFAULT.png'
```

**Comment by xiphirx** [comment]
Thanks for the flag. It seems like the default value for this flag was flipped when I rewrote the plugin. Sorry about that! I'll submit a fix

**Comment by Egorand** [comment]
Thanks!

**Comment by xiphirx** [comment]
7dba891a53d2b7108e14cbcc3974c8b1dd417af2
