### ISSUE TITLE
ScreenshotsPluginExtension's addDeps parameter doesn't work

### ISSUE THREAD

**Issue by timemanx** [facebook/screenshot-tests-for-android#192]
The `ScreenshotsPlugin` reads the value of `ScreenshotsPluginExtension`'s `addDeps` field in it's `apply` method right after the extension is initialised.
```
screenshotExtensions = extensions.create("screenshots", ScreenshotsPluginExtension::class.java)

if (screenshotExtensions.addDeps) {
    project.dependencies.add("androidTestImplementation", "$DEPENDENCY_GROUP:$DEPENDENCY_CORE:${ScreenshotTestBuildConfig.VERSION}")
}
```
Since it's all inside the apply method, `ScreenshotsPluginExtension`'s properties haven't been set yet in the gradle file, so `addDeps` returns the value that is initially set in the `ScreenshotsPluginExtension` which is `true`.

**Comment by lwasyl** [comment]
I submitted https://github.com/facebook/screenshot-tests-for-android/pull/216 which fixes this. We could actually use this because of what looks like a weird dependency mismatch with 0.9.0 that I can't pinpoint. Depending on the core library non-transitively might help
