### ISSUE TITLE
Crash on anonymous View

### ISSUE THREAD

**Issue by ibartj** [facebook/screenshot-tests-for-android#198]
I had troubles running the record script on a layout containing anonymous View which overrides its onDraw() method. I'm no python programmer, but changing this:
`node[KEY_CLASS]` and `node['class']`
in pull_screenshots.py to this:
`node.get(KEY_CLASS, 'View')` and `node.get(KEY_CLASS, 'View')`
has helped me. Should I open a pull request or what are your thoughts about this?

**Comment by xiphirx** [comment]
Yeah it seems reasonable to default to "View" when its an anonymous class.
