### ISSUE TITLE
Documentation page is loading insecure resources

### ISSUE THREAD

**Issue by rowillia** [facebook/screenshot-tests-for-android#2]
<img width="539" alt="screen shot 2015-10-06 at 3 34 30 pm" src="https://cloud.githubusercontent.com/assets/808798/10324613/d3a27c98-6c3f-11e5-8693-024e77428605.png">

**Comment by diki** [comment]
Documentation page redirects to http://code.facebook.com

**Comment by tdrhq** [comment]
@Roy removed the link to nuclide.io, hope it didn't break any other CSS business on the page
@diki Fixed link from readme, Thanks!
