### ISSUE TITLE
Run screenshot tests without other instrumentation tests

### ISSUE THREAD

**Issue by gpeal** [facebook/screenshot-tests-for-android#20]
Is there a way to run the screenshot tests without also running all other instrumentation tests (like espresso)? This adds a significant amount of time to the screenshot testing task and it seems like it should be able to be run independently.

**Comment by tdrhq** [comment]
Sort of: it's similar to however you'd run specific instrumentation tests.

I don't know if the gradle plugin provides a way to run specific tests. (If it doesn't then you can run specific tests using 'adb shell am instrument' directly). But once you run the instrumentation tests that you care about, you can do 'gradle pullScreenshots'

**Comment by tdrhq** [comment]
Closing for now, let me know if there's something I can do to make this an easier experence.

**Comment by OlehHaidaienko** [comment]
Probably there is some approach, so I created gradle task, where specified classes which I need to run
```
task UITest() {
    android.defaultConfig.testInstrumentationRunnerArguments.class =
            'com.example.foo.ExampleClass1,com.example.bar.ExampleClass2'
}
```
after that I have executed in console
`gradle UITest recordMode screenshotTests`
Also you can specify other [am instrument options](https://developer.android.com/studio/test/command-line.html#AMSyntax)
