### ISSUE TITLE
Program type already present: com.google.protobuf.AbstractProtobufList :::  {"kind":"error","text":"Program type already present: com.google.protobuf.AbstractProtobufList","sources":[{}],"tool":"D8"}

### ISSUE THREAD

**Issue by jyotirmayghosh** [facebook/screenshot-tests-for-android#209]
I just started with Google cloud speech API.
I checked throughout the code but unable to find the error.
I checked with the sample application [here](https://github.com/GoogleCloudPlatform/android-docs-samples/tree/master/speech/Speech) which is working fine.

Below is the build log:

Executing tasks: [:app:assembleDebug]

The com.google.protobuf plugin was already applied to the project: :app and will not be applied again after plugin: android
:app:checkDebugClasspath UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:extractDebugProto UP-TO-DATE
:app:extractIncludeDebugProto UP-TO-DATE
:app:extractProto UP-TO-DATE
:app:generateDebugProto UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceDebug UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:app:compileDebugJavaWithJavac
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
AGPBI: {"kind":"error","text":"Program type already present: com.google.protobuf.AbstractProtobufList","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.google.protobuf.AbstractProtobufList

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
24 actionable tasks: 5 executed, 19 up-to-date

Can anyone help me to solve this issue.

**Comment by xiphirx** [comment]
This is unrelated to this project.
