### ISSUE TITLE
`variant.getConnectedInstrumentTest()` is obsolete

### ISSUE THREAD

**Issue by matsomatic** [facebook/screenshot-tests-for-android#210]
Hi 👋

I'm in the process of following the instructions for setting up screenshot tests. When modifying build.gradle and syncing I get a warning: 

`WARNING: API 'variant.getConnectedInstrumentTest()' is obsolete and has been replaced with 'variant.getConnectedInstrumentTestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getConnectedInstrumentTest(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules:`

I couldn't see it reported before, and looks like it should be addressed.

Stacktrace as per the instruction in the warning attached.

[stacktrace.txt](https://github.com/facebook/screenshot-tests-for-android/files/2796135/stacktrace.txt)

**Comment by xiphirx** [comment]
Hey, thanks for the report! It seems like a straightforward API switch.

**Comment by cdeange** [comment]
@xiphirx will this be addressed soon? The aforementioned _"end of 2019"_ is approaching soon.

**Comment by xiphirx** [comment]
Thanks for the ping, I'll see when I can prioritize this.

**Comment by KaurManjot** [comment]
Yes. please prioritize this. It is blocking us from running our tests

**Comment by xiphirx** [comment]
If this is highly urgent I'm happy to review any PRs that you may have
