### ISSUE TITLE
Save failure diffs in folder

### ISSUE THREAD

**Issue by m-ruhl** [facebook/screenshot-tests-for-android#211]
Hello,

the iOS counterpart of screenshot tests, saves failed diffs in a folder `FailureDiffs`
So Helper-Apps like [FBSnapshotsViewer](https://github.com/Antondomashnev/FBSnapshotsViewer) can listen to file changes and show the failed diffs.
Also you are able to see the diff in detail with tools like: https://www.kaleidoscopeapp.com

Thanks
Michael

**Comment by pkpdeveloper** [comment]
Hello guys,
Any update on this issue. If you can approve I can work on it. 

Thanks

**Comment by kirillzh** [comment]
#225 addresses this feature request.
