### ISSUE TITLE
Program type already present: android.support.compat.R$attr

### ISSUE THREAD

**Issue by mohitrajput987** [facebook/screenshot-tests-for-android#218]
While using these libraries-
```gradle
facebookScreenshotTestCommon = "com.facebook.testing.screenshot:layout-hierarchy-common:0.9.0"
facebookScreenshotTestLitho = "com.facebook.testing.screenshot:layout-hierarchy-litho:0.9.0"
```

I'm getting "Program type already present: android.support.compat.R$attr" error while generating release build. In debug build, it's working fine.

**Comment by xiphirx** [comment]
dupe of #217

**Comment by mohitrajput987** [comment]
> dupe of #217

It's not the duplicate of #217 
Please see both issue again.
