### ISSUE TITLE
Cannot run connectedAndroidTest

### ISSUE THREAD

**Issue by IgorGanapolsky** [facebook/screenshot-tests-for-android#219]
In following the README, I tried `./gradlew :core:connectedAndroidTest`.  Got the following error: 
> > Task :core:compileDebugAndroidTestJavaWithJavac FAILED
/Users/igor.ganapolsky/workspace/git/facebook/screenshot-tests-for-android/core/src/androidTest/java/com/facebook/testing/screenshot/internal/AlbumImplTest.java:128: error: cannot find symbol
    mAlbumImpl.openViewHierarchyFile("foo").close();
              ^
  symbol:   method openViewHierarchyFile(String)
  location: variable mAlbumImpl of type AlbumImpl
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
FAILURE: Build failed with an exception.

**Comment by xiphirx** [comment]
Yeah with the recent changes where we put all images in a single zip rather than a directory, this caused these tests to break. Thanks for pointing it out, I'll see when I can get around to fixing them.

**Comment by xiphirx** [comment]
Tests have been fixed.
