### ISSUE TITLE
Make mTileSize configurable to avoid tiling when not required

### ISSUE THREAD

**Issue by bootstraponline** [facebook/screenshot-tests-for-android#22]
I'm seeing 7 files being created per screenshot call. Is it not possible to get just a single png? I don't want a debug dump and tiled images. None of the images are a complete screenshot of what's on the screen.

> Screenshot.snapActivity(getActivity()).setName(name).record();

```
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_0_1.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_0_2.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_1_0.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_1_1.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_1_2.png
com.my.pkg.test.LoginTest-loginRejectsInvalidCredentials_dump.xml
```

**Comment by tdrhq** [comment]
if you do a "gradle recordMode screenshotTests", it should generate the full pngs and "record" it to a directory.

**Comment by bootstraponline** [comment]
Unfortunately that doesn't help. My use case is running on [Google's Cloud Test Lab](https://developers.google.com/cloud-test-lab/) which has no support for Gradle. 

Is there no Java API to take a full png screenshot (and delete the tiles/xml files)?

**Comment by bootstraponline** [comment]
FYI the way cloud test lab currently works is it dumps everything from `/sdcard/screenshots/` into a Screenshots view in the UI. The current `screenshot-tests-for-android` makes a mess because there are a bunch of intermediary files and no full screenshots.

I guess the short term work around is for me to [go back to Spoon](https://github.com/square/spoon/blob/ccbffd7e5718b2c991bf029dad04730bb8fd5410/spoon-client/src/main/java/com/squareup/spoon/Spoon.java#L56) which creates exactly one png per screenshot call. Ideally the facebook lib would have an on device stitching solution that doesn't depend on 3rd parties (gradle/python). It's a simple use case: take a screenshot.

**Comment by tdrhq** [comment]
Hmm, the stitching can't be done on device without external libraries. The reason for the stitching is that we can't store the whole bitmap in memory. (We support really large views)

There were some other libraries that directly constructed the result image files onto the filesystem without having it all stored in memory, but I didn't want an external dependency for that use case.

If you think your device/emulator has enough memory that such stitching isn't worthwhile, try increasing this to a larger number so that it can completely contain your screenshots: https://github.com/facebook/screenshot-tests-for-android/blob/master/core/src/main/java/com/facebook/testing/screenshot/internal/ScreenshotImpl.java#L56

**Comment by tdrhq** [comment]
we should also make that parameter configurable so you don't have to rebuild from source

**Comment by bootstraponline** [comment]
> There were some other libraries that directly constructed the result image files onto the filesystem without having it all stored in memory, but I didn't want an external dependency for that use case.

What libs are they? Might be better for my use case.

**Comment by tdrhq** [comment]
It's been a while since I've looked at that, I'm not able to find it/them at the moment. Do consider just increasing the tile size, that's really the easiest solution as long as you can give it enough heap.

**Comment by bootstraponline** [comment]
Ok, even if I do that then there's still no option to prevent the xml files from being generated. I don't want random files in storage because I'm charged $$ for them.

**Comment by tdrhq** [comment]
Happy to accept a pull request to make the XML file configurable, but for now I'm renaming this task just to make the tile size configurable which I'll try to do soon

**Comment by bootstraponline** [comment]
> Happy to accept a pull request to make the XML file configurable


Something like this?

```java
public interface RecordBuilder {
    public RecordBuilder disableDumpFile();
```

**Comment by tdrhq** [comment]
nope, pass it as an instrumentation argument. I wouldn't want to expose this every time somebody is doing code completion while trying to create a screenshot.

**Comment by bootstraponline** [comment]
Makes sense. Should the tile size be configured the same way (instrumentation argument)?

**Comment by tdrhq** [comment]
That would be my plan, yes. Feel free to send a pull request for that too though

**Comment by bootstraponline** [comment]
Submitted #23 for the no dump flag.
