### ISSUE TITLE
[Build Error] Duplicate class

### ISSUE THREAD

**Issue by rcd27** [facebook/screenshot-tests-for-android#221]
There are similar classes in different modules and gradle can't complete the build with multiple specific errors like:
`Duplicate class android.support.coreui.R$bool found in modules jetified-core-0.9.0.jar (com.facebook.testing.screenshot:core:0.9.0) and jetified-layout-hierarchy-common-0.9.0.jar (com.facebook.testing.screenshot:layout-hierarchy-common:0.9.0)`

**Comment by xiphirx** [comment]
Dupe of #217
