### ISSUE TITLE
Could not find com.facebook.testing.screenshot:plugin:0.11.0-SNAPSHOT

### ISSUE THREAD

**Issue by Usha27-star** [facebook/screenshot-tests-for-android#226]
A problem occurred configuring project ':sample'.
> Could not resolve all artifacts for configuration ':sample:classpath'.
   > Could not find com.facebook.testing.screenshot:plugin:0.11.0-SNAPSHOT.
     Searched in the following locations:
       -m2/repository/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/maven-metadata.xml
       -.m2/repository/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.pom
       .m2/repository/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.jar
       - https://jcenter.bintray.com/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.jar
       - https://dl.google.com/dl/android/maven2/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/testing/screenshot/plugin/0.11.0-SNAPSHOT/plugin-0.11.0-SNAPSHOT.jar

**Comment by xiphirx** [comment]
We don't have a job that auto-uploads snapshots (yet). You will need to install them locally: ./gradlew core:install , plugin:install, etc
