### ISSUE TITLE
Scrambled screenshot

### ISSUE THREAD

**Issue by lwasyl** [facebook/screenshot-tests-for-android#235]
Sometimes when I run screenshots, I get scrambled view like this:

![image](https://user-images.githubusercontent.com/3951580/70514461-fcfde080-1b33-11ea-8d69-5a92814403e0.png)

Seems like it's one tile getting shifted:

![image](https://user-images.githubusercontent.com/3951580/70514534-2454ad80-1b34-11ea-8335-101f5d387094.png)

It is the same also in the recorded screenshot, it's not only issue with HTML preview. It does seem to happen when the text that's being set in edit text (via binding) scrolls

**Comment by xiphirx** [comment]
You will need to ensure that your view is completely idle before taking a screenshot, otherwise things like this will happen.

**Comment by lwasyl** [comment]
@xiphirx Actually we're hitting this again, but this time I'm sure everything is idle (according to Espresso). This seems to only happen for contents in a `ScrollView`, and only when the tested view is not part of an activity's content view. If it is, the issue goes away. Any idea what might be happening here?
