### ISSUE TITLE
Exclude area of screenshot

### ISSUE THREAD

**Issue by tobiasKaminsky** [facebook/screenshot-tests-for-android#236]
First, let me thank you for your great library.

I created a test case, which has a time string in it, that I get from a remote server, which I cannot control. 
On selenium there was the possibility to make parts of the comparison screenshot transparent and thus a changed part, e.g. the above time string, will not let the test fail.

Is there something similar in this library?

(If not, I need to find a way to mock this and have fixed dates)

**Comment by xiphirx** [comment]
There isn't, you would need to add a view or something yourself to block out the problematic area.

Could you also not just grab whatever view its in and set its visibility to GONE ?

**Comment by tobiasKaminsky** [comment]
> There isn't, you would need to add a view or something yourself to block out the problematic area.

On selenium one can cut out the problematic parts in reference images and replace them with transparent background.
Then everything on new-taken-screenshot can match against this area, so nothing will fail.
I guess this is just handled somewhere in their image comparison lib.



> Could you also not just grab whatever view its in and set its visibility to GONE ?

That is a nice workaround, I'll give it a try!
