### ISSUE TITLE
Allow Plugin to specify screenshot directory under test

### ISSUE THREAD

**Issue by kylannjohnson** [facebook/screenshot-tests-for-android#24]
It would be great to specify the location of the generated screenshots to the plugin as an alternative to using an adb pull to retrieve them each time.  

For our CI build, we run our instrumentation tests in separate runs across multiple devices in parallel.  IF we could specify the location of the screenshots, we could perform one verification at the end of the build

**Comment by yogurtearl** [comment]
@tdrhq would you accept a PR for this change?

**Comment by tdrhq** [comment]
Sorry for the delay in my reply. I would happily accept a PR!

**Comment by kylannjohnson** [comment]
@tdrhq no worries.  I'll get you PR soon

**Comment by kylannjohnson** [comment]
@tdrhq I submitted my PR #33 to address this issue.  Please let me know if you have any questions or concerns.  Cheers!

**Comment by tdrhq** [comment]
closing since the PR is merged
