### ISSUE TITLE
Support scoped storage

### ISSUE THREAD

**Issue by SUPERCILEX** [facebook/screenshot-tests-for-android#240]
See https://github.com/facebook/screenshot-tests-for-android/issues/162#issuecomment-528282299. That was the issue for me.

**Comment by TimoPtr** [comment]
This fix(hack) the issue https://github.com/facebook/screenshot-tests-for-android/pull/273

**Comment by SUPERCILEX** [comment]
Closing old issues.

**Comment by Venkat-juju** [comment]
The PR #273  is still not merged it seems.
