### ISSUE TITLE
Not able to build with com.android.tools.build:gradle:3.6.0

### ISSUE THREAD

**Issue by andresfabreu** [facebook/screenshot-tests-for-android#241]
I get the following error when try to build the project with com.android.tools.build:gradle:3.6.0:

```
ERROR: Unable to find method 'com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

I saw that there is already a commit for this issue, it will be released soon, is there a snapshot for it?

Thanks in advance.

**Comment by pawegio** [comment]
It was closed in https://github.com/facebook/screenshot-tests-for-android/issues/233
I also hope it will be released soon.

**Comment by lwasyl** [comment]
@xiphirx Could you please release this or let us know if there's something blocking the release? Or if  there are snapshots we can use in the meantime?

**Comment by xiphirx** [comment]
https://github.com/facebook/screenshot-tests-for-android/commit/805a93fdf2ea49af1f324112673f191b08f833ea
