### ISSUE TITLE
sdcard not accessible

### ISSUE THREAD

**Issue by EmilMcDuck** [facebook/screenshot-tests-for-android#256]
Hey, i stumbled across a potential issue, 
Environment.getExternalStorageDirectory() does return my /storage/emuated/0 directory, while the getSdcardDir in ScreenshitDirectories.java returns /sdcard which doesn't seem to exist. Besides that it would be cool if it was possible to specify the screenshot directory path.

**Comment by EmilMcDuck** [comment]
`java.lang.RuntimeException: Failed to create the directory /sdcard/screenshots/xxxx.test/screenshots-default for screenshots. Is your sdcard directory read-only?
	at com.facebook.testing.screenshot.internal.ScreenshotDirectories.getSdcardDir(ScreenshotDirectories.java:126)`

**Comment by EmilMcDuck** [comment]
android:requestLegacyExternalStorage="true" fixed the problem

**Comment by oradkovsky** [comment]
@dscheucher for Android 11, the above fix will not work
