### ISSUE TITLE
Change the layout but the verifyDebugAndroidTestScreenshotTest pass

### ISSUE THREAD

**Issue by ViniciusGuardieiroSousa** [facebook/screenshot-tests-for-android#265]
I made a simple layout, and I run the "gradlew recordDebugAndroidTestScreenshotTest", the image gerated was 
![image](https://user-images.githubusercontent.com/54741328/93398001-1cf3ca80-f851-11ea-99a8-4df663602f37.png)
Then I change the button color and run the "gradlew verifyDebugAndroidTestScreenshotTest", and my image was
![image](https://user-images.githubusercontent.com/54741328/93398267-a0152080-f851-11ea-85e3-65a27b847865.png)
I follow this getting started http://facebook.github.io/screenshot-tests-for-android/#getting-started,
In the #125 I saw the "./gradlew verifyDebugAndroidTestScreenshotTest" doesn't report when to image are diferent, how I'll compare this? I need to create a test to load all screenshots and check than? Or Already exist some funcition to do that?

**Comment by xiphirx** [comment]
#125 is talking about showing a visual diff report. The verify task will fail if the images are different.
