### ISSUE TITLE
Problem on apply plugin: 'com.facebook.testing.screenshot'

### ISSUE THREAD

**Issue by stephen1706** [facebook/screenshot-tests-for-android#266]
Hi, I am facing a problem on applying the plugin to my module. I am trying to apply the plugin to my library module (although applying to my app module also face the same issue). I am guessing the plugin might conflict with other plugin, but can't really tell exactly which one. I put the `apply plugin: 'com.facebook.testing.screenshot'` at module level `build.gradle`, and `classpath 'com.facebook.testing.screenshot:plugin:0.13.0` at root level `build.gradle`. But when I try to test it on new empty project the plugin can be integrated successfully.
This is the error log, is there a way to find what is the root cause of this:

```
ERROR: Unable to find method 'com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Lorg/gradle/api/file/DirectoryProperty;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by xiphirx** [comment]
What version of Gradle are you using?

**Comment by stephen1706** [comment]
@xiphirx It appears my project doesn't have `classpath 'com.android.tools.build:gradle:3.6.3'` defined because my project is a library.

**Comment by mitsest** [comment]
I 'm using 3.3.2 . Is this an issue?
Which is the minimum gradle version you support?
