### ISSUE TITLE
Record screenshots without installing the APK

### ISSUE THREAD

**Issue by Gunashree-R-V** [facebook/screenshot-tests-for-android#270]
As per the documentation, 
```
record<App Variant>ScreenshotTest - Installs and runs screenshot tests, then records their output for later verification
```

Is there a way to record screenshots without installing APK(i.e., without running `package<App Variant>AndroidTest`)?

I'm able use `am instrument` command to invoke the tests from `adb`. The screenshots are stored in the device.

However, after this step I would like to pull the recorded screenshots and save under `recordDir` through command line. Is this possible?

**Comment by xiphirx** [comment]
You can use the `pull<App Variant>Screenshots` task https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/kotlin/com/facebook/testing/screenshot/build/PullScreenshotsTask.kt#L28

**Comment by Gunashree-R-V** [comment]
@xiphirx, 
```pull<App Variant>Screenshots``` task is not adequate. 

It just pulls the screenshots and meta data from device. But it doesn't update the screenshots record directory with new screenshots.

I'm basically looking for a task that can perform ```pull screenshots``` task with record parameter as true.

Something like this, I would like perform a task which does just does this step.
```
python -m android_screenshot_tests.pull_screenshots --apk test.apk --temp-dir /build/screenshotsDevDebugAndroidTest --record screenshots. 
```

**Comment by Gunashree-R-V** [comment]
@xiphirx,
Any updates on this?
I'm currently blocked on this.

**Comment by xiphirx** [comment]
Couldn't you just create your own task? `PullScreenshotsTask` is an `open` class.
