### ISSUE TITLE
Integrate screenshot test library in AOSP

### ISSUE THREAD

**Issue by tarolechaitanya** [facebook/screenshot-tests-for-android#279]
Hi, 
I am developing an application for AOSP. I would like to do screenshot testing for the same.
I am developing system application so it has makefile based structure.
However I do not find support for system apps for screenshot library.
I would like to integrate screenshot library in AOSP source code.

Can it be possible to integrate and use it ?
1. Integrate in AOSP
2. Take screenshots on Makefile/Blueprint based project structure
3. Configuration of library

Thanks.

**Comment by xiphirx** [comment]
Its possible, but wont be directly supported by this project. The library just outputs images to a specific directory on the device that the plugin later pulls via adb pull. You would need to perform the adb pull on your own and the verification. You can likely reuse the python scripts in the plugins directory to do this.
