### ISSUE TITLE
Chat panel 

### ISSUE THREAD

**Issue by abhishekmedipta** [facebook/screenshot-tests-for-android#31]
There is a bug in facebook in chat, there is a chat panel in right side of facebook page, when there are lots of people are online and that time, if we scroll the scroll bar, then last user are not showing properly.

see the attachment..
![screenshot 100](https://cloud.githubusercontent.com/assets/16331239/14066436/bd95ad6c-f466-11e5-9b02-03f9101c972c.png)
![screenshot 100 _3](https://cloud.githubusercontent.com/assets/16331239/14066437/bdb8eb92-f466-11e5-9fea-64898e29b285.png)

**Comment by tdrhq** [comment]
I'm closing this out, but I'm sending a link to this to the relevant internal team for triaging.

**Comment by abhishekmedipta** [comment]
@tdrhq still this issue are not resolved...
