### ISSUE TITLE
Inflating views with application context does not use styles

### ISSUE THREAD

**Issue by jpkrause** [facebook/screenshot-tests-for-android#32]
I noticed an issue with inflating layouts using something like 
````
LayoutInflater layoutInflater = LayoutInflater.from(InstrumentationRegistry.getTargetContext());
````
in that this uses a context that does not honor the use of attributes in the layout xml view tags such as 
````
style="@style/TextAppearance.AppCompat.Title"
````
I was able to work around this issue by creating an `ActivityTestRule` and getting the layout inflater from the activity: 
````
LayoutInflater layoutInflater = activityTestRule.getActivity().getLayoutInflater();
````
While this does work, it is not quite as fast since the activity needs to be started before the test is run. Is there a way to include styles in the context so that using an activity is not necessary? I tried `InstrumentationRegistry.getTargetContext().setTheme(R.style.AppTheme);` with no avail.

**Comment by tdrhq** [comment]
Yep, use ContextThemeWrapper to wrap over the context you already have. Otherwise, by default app themes are only applied to Activities.

**Comment by jpkrause** [comment]
Ah, perfect! Thank you.
