### ISSUE TITLE
Verify wiki for "Running screenshot tests without other instrumentation tests"

### ISSUE THREAD

**Issue by BenjiLee** [facebook/screenshot-tests-for-android#36]
Greetings @tdrhq,

  I have added a wiki to this repository's wiki pages. Little did I know there is no verification/PR like process for adding wiki pages. Could you verify that https://github.com/facebook/screenshot-tests-for-android/wiki/Running-screenshot-tests-without-other-instrumentation-tests is 👍  to be on this repository's wiki?

Thanks,
BenjiLee

**Comment by tdrhq** [comment]
This seems fine, however I'm going to edit this and file this under a Hints and FAQ section

(Although, most of our documentation is on the github page.. send me a pull request for gh-pages branch if you want to change that)
