### ISSUE TITLE
recordMode not saving files locally?

### ISSUE THREAD

**Issue by georgepapas** [facebook/screenshot-tests-for-android#40]
Hi, 

As I understand it, running

```
./gradlew recordMode screenshotTests
```

should save generated pngs to a local screenshot directory. Is the intention here that this will be a directory under the project root named `screenshots` or the tmp directory that gets generated?

I'm seeing files in the temp directory, but nothing makes it to my screenshots directory.

**Comment by kylannjohnson** [comment]
@georgepapas do you mean this? 

`./gradlew recordMode pullScreenshots`

**Comment by georgepapas** [comment]
Yes.

**Comment by cperry-gpsw** [comment]
I'm also curious about this. 

Running:

```bash
/gradlew screenshotTests
```

I get screenshots put into a folder on my machine under:

> /var/folders/n0/_29wvcn97sv_w5mttzmkvf3cm1897l/T/screenshotsIU5pAP

This is definitely not where I want these. How do I get the plugin to put these into a "screenshots" folder in project directory?

**Comment by ijwhelan** [comment]
Having the same problem here too.

**Comment by georgepapas** [comment]
Looks like this project is no longer maintained...

**Comment by tdrhq** [comment]
Sorry for the delay: ./gradlew screenshotTests *will* write to a temporary directory, the intention is that this is used while doing iterative development (kind of like TDD)

./gradlew recordMode screenshotTests should save it to the directory specified in the config.. if it's not, then that's definitely broken.

**Comment by jiriadamec** [comment]
Could you please add parameter to the plugin to specify where to put temporary and result files?
I propose this solution [http://pastebin.com/5SgRAQ5n](Source).

Thanks in advance
