### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by cperry-gpsw** [facebook/screenshot-tests-for-android#41]
I'm having an issue trying to run 

``` groovy
gradle recordMode screenshotTests
```

It seems I'm missing a Python library. I tried to install it via:

``` bash
pip install PIL
```

but I get the following message

``` bash
Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

However, installing Pillow works:

``` bash
pip install Pillow
```

I tried running `gradle recordMode screenshotTests` again after, but I still get the same message.

I know nothing about Python, please help.

**Comment by cperry-gpsw** [comment]
For anyone else that has this issue, running the following fixed it for me:

```bash
pip install pillowcase
```

**Comment by durbon** [comment]
If you still have problems installing Pillow and Pillowcase in mac you can use.

The compiler that comes with Xcode 5.1 treats unknown passed parameters as errors.

We're telling it to ignore those "errors" More info here http://stackoverflow.com/a/23094087/907493

`sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install pillow`

`sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install pillowcase`

**Comment by jkwiecien** [comment]
That should be in the main doc...
