### ISSUE TITLE
pullScreenshots fails with "Expected task ':app:packageDebugAndroidTest' output files to contain exactly one file, however, it contains 2 files"

### ISSUE THREAD

**Issue by gpeal** [facebook/screenshot-tests-for-android#42]
The test seems to complete successfully but Gradle complains with the error in the title.
I ran `./gradlew  --daemon :app:screenshotTests`.

**Comment by gpeal** [comment]
I'm still unable to get this working in my library due to the error above. I'm using version `0.4.1` and here is the gradle logs with `--info --debug`
https://gist.github.com/gpeal/8ce20024af55a710c8be50e5ea489e6e

**Comment by gpeal** [comment]
The project is a gradle project with 2 modules, an Android library and an Android application. The application depends on the library and only the application applies the plugin.
There are no custom flavors.

**Comment by niravnagda** [comment]
@gpeal did you solve this issue?

**Comment by brianguertin** [comment]
I ran into this issue when updating to `com.android.tools.build:gradle:2.2.0`.

Switching back to `com.android.tools.build:gradle:2.1.3` works around the issue, so it appears to be an incompatibility with version 2.2.0 specifically.

**Comment by tdrhq** [comment]
I was able to repro on 2.2.0, thanks for the info @brianguertin!

Trying to figure this out, will keep you posted. (I'm not exactly a gradle expert, so any hints are welcome)

**Comment by tdrhq** [comment]
Okay fix has landed: https://github.com/facebook/screenshot-tests-for-android/commit/d84e7ab140e8d7b111bb906775c370e2f2b06d41

If somebody can :plugin:install locally and verify that this works for them, I can publish a new minor release. Thanks!

**Comment by gpeal** [comment]
I can't test the local install today (how does :plugin:install work by the way?).
However, a couple of weeks ago, I made a local fix very similar to yours and it fixed it for me so if you want to bump the version and push to maven, I can try that.

**Comment by tdrhq** [comment]
@gpeal, :plugin:install would install it to your local maven repository, so then you can use it to build your actual app instead of downloading the jar from mavencentral or the likes.

In any case, I'll bump up the version today and close out this task then.

**Comment by tdrhq** [comment]
Version bumped to 0.4.2, thanks for the report!
