### ISSUE TITLE
latest version numbers - changelog

### ISSUE THREAD

**Issue by athkalia** [facebook/screenshot-tests-for-android#43]
Hey there,

it's good to have the version number up to date both in this github page and here:
http://facebook.github.io/screenshot-tests-for-android/

Also it's super important to keep a changelog to reflect all changes done.

Cheers,
Sakis

**Comment by tdrhq** [comment]
Thanks for the report, I've updated the github page, and I've also added a changelog starting from 0.4.2 which I released today
