### ISSUE TITLE
BUCK support

### ISSUE THREAD

**Issue by masterginger** [facebook/screenshot-tests-for-android#46]
Hey, do you have any plan to support BUCK? If so, what's the timeline?
We're using BUCK instead of gradle at work, we're looking for some command line (e.g. 'adb shell instrument') to run screenshot-tests-for-android, so it would great if you can provide any pointer to the gradle task implementation or how we should do if we need to get BUCK support by ourselves. Appreciate your help!

**Comment by tdrhq** [comment]
We don't have support inside of buck, however: it's reasonably straightforward to use buck with some of the scripts provided in the repo (basically, call buck test on your android_instrumentation_test() target, followed by the pull_screenshots.py in this repo). I'll try to wrap this into a script for easier use.
