### ISSUE TITLE
Verify fails for no reason

### ISSUE THREAD

**Issue by jkwiecien** [facebook/screenshot-tests-for-android#47]
I did ```recordMode screenshotTests ``` and then without changing anything, right after I ran ```verifyMode screenshotTests```. I have just one screen covered now. The test failed with:
```Image /var/folders/xx/ylzhl52j66xcf367d8d502tc0000gn/T/tmpyoCni4/<package>.LoginScreenTest_loginAndLogout.png is not same as screenshots/<package>.LoginScreenTest_loginAndLogout.png```

I compared screenshots manually and I don't see any differences. Attaching both, recorded and verified screnshoots. Those look the same to me. If it painted some colour differences, that would be great.

<img width="1002" alt="screenshots" src="https://cloud.githubusercontent.com/assets/3003159/20305603/9b517236-ab36-11e6-9ba8-46ef92d4fe1f.png">

EDIT:
It passed once today. Gussing that alghoritm is too sensitive for changes

**Comment by xiphirx** [comment]
There is a change in your screenshot, the "E-postadress" in your TextInputLayout. Closing
