### ISSUE TITLE
How to save screenshots on PC disk, instead of phone storage?

### ISSUE THREAD

**Issue by SergeyShustikov** [facebook/screenshot-tests-for-android#49]
When I run 

    gradlew recordMode screenshotTest

all screenshots by deafult stores in phone storage in screenshot/ folder

And my question is : how I can setup path to saving screenshots.
We want to use the next scenario :

1) Execute gradlew recordMode screenshotTest
2) All recorded screenshots should save into app/screenshots folder on PC.
3) Run gradlew clean build in pair with verifyMode screenshotTest
4) If all is ok commit and push into CI
5) If not - fix problems and make step 4;

But. We are developers and we all know about human factor. Sometimes developers could forget to execute verifyMode and push changes without checking. 

We have a CI. And I saw that this library works with CI, but saving in PC storage will be very helpfull from automated point of view. Thanks!

**Comment by SergeyShustikov** [comment]
Sorry, didn't noticed that test results saving into app folder automatically.

**Comment by tdrhq** [comment]
Is there a way (in terms of what messages we output etc.) to have made this more obvious? I'll be happy to accept a pull request if so

**Comment by SergeyShustikov** [comment]
I'll be happy too, if this functionality will be exist :)
