### ISSUE TITLE
Not able to make tests work with AndroidJunitRunner

### ISSUE THREAD

**Issue by naderz** [facebook/screenshot-tests-for-android#51]
While trying to run screenshots with my UI tests, i am always getting no tests found the moment i add the screenshot plugin.
I extended AndroidJunitRunner i am always getting that error.

Can you please provide a working example with tests that using AndroidJunitRunner and not instrumentedTestcase that is deprecated

**Comment by tdrhq** [comment]
This is correct, we didn't want to implicitly force a dependency on testing-support-lib so we don't provide a runner based off of AndroidJUnitRunner. You can however extend one yourself and call into https://github.com/facebook/screenshot-tests-for-android/blob/master/core/src/main/java/com/facebook/testing/screenshot/ScreenshotRunner.java

(call onCreate() from your custom Runners onCreate, and onDestroy() from finish()). 

If you send me a pull request with a simple example of a custom runner using AndroidJUnitRunner I'll be happy to accept! Let me know if this solution works in the meantime.

**Comment by naderz** [comment]
Thanks for you answer :) 

I did that already : 

> class SSRunner extends AndroidJUnitRunner {
> 
>     @Override
>     public void onCreate(Bundle arguments) {
>         MultiDex.install(getTargetContext());
>         ScreenshotRunner.onCreate(this, arguments);
>         super.onCreate(arguments);
>     }
> 
>     @Override
>     public void finish(int resultCode, Bundle results) {
>         ScreenshotRunner.onDestroy();
>         super.finish(resultCode, results);
>     }
> }


And gradle looks like this : 

> apply plugin: 'com.android.application'
> 
> android {
>     compileSdkVersion 25
>     buildToolsVersion "25.0.0"
>     defaultConfig {
>         multiDexEnabled true
>         applicationId "com.example.nadera.myapplication"
>         minSdkVersion 15
>         targetSdkVersion 25
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "com.example.nadera.myapplication.SSRunner"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
>         exclude group: 'com.android.support', module: 'support-annotations'
>     })
>     compile 'com.android.support:appcompat-v7:25.1.0'
>     compile 'com.android.support:design:25.1.0'
>     compile 'com.android.support:multidex:1.0.1'
>     testCompile 'junit:junit:4.12'
> }
> 
> apply plugin: 'com.facebook.testing.screenshot'
> 
> 

I seriously cant figure out what is really going wrong

**Comment by naderz** [comment]
Ill happily do a PR for this when i get it working. @tdrhq

**Comment by tdrhq** [comment]
You need to also have your custom instrumentation set up in your AndroidManifest

**Comment by naderz** [comment]
@tdrhq I tried that still not working can you give a sample of the instrumation tag that should be added to the manifest ?

**Comment by tdrhq** [comment]
```
 <manifest>  <instrumentation
    android:name="com.example.nadera.myapplication.SSRunner"
    android:targetPackage="com.example.nadera.myapplication.test" />
</manifest>
```

**Comment by naderz** [comment]
@tdrhq  added this to manifest and still not working ... targetPackage is red so its not being recognised by the IDE ... 
I tried adding this tag to androidTest manifest and to the main manifest and still no luck something interesting that i found is that in the build package i looked at the manifest being generated and saw this : 

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.nadera.myapplication.test" >
> 
>     <uses-sdk
>         android:minSdkVersion="15"
>         android:targetSdkVersion="25" />
> 
>     <instrumentation
>         android:name="com.facebook.testing.screenshot.ScreenshotTestRunner"
>         android:functionalTest="false"
>         android:handleProfiling="false"
>         android:label="Tests for com.example.nadera.myapplication"
>         android:targetPackage="com.example.nadera.myapplication" />
> 
>     <application>
>         <uses-library android:name="android.test.runner" />
>     </application>
> 
> </manifest>


Its like its totally ignoring the SSRunner

**Comment by tdrhq** [comment]
Oh I forgot that if you're using gradle then gradle modifies the AndroidManifest for you, so something like this: https://github.com/facebook/screenshot-tests-for-android/blob/master/core/build.gradle#L45

**Comment by naderz** [comment]
```
 apply plugin: 'com.android.application'
 
 android {
     compileSdkVersion 25
     buildToolsVersion "25.0.0"
     defaultConfig {
         multiDexEnabled true
         applicationId "com.example.nadera.myapplication"
         minSdkVersion 15
         targetSdkVersion 25
         versionCode 1
         versionName "1.0"
         testInstrumentationRunner "com.example.nadera.myapplication.SSRunner"
     }
     buildTypes {
         release {
             minifyEnabled false
             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
         }
     }
 }
 
 dependencies {
     compile fileTree(dir: 'libs', include: ['*.jar'])
     androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
         exclude group: 'com.android.support', module: 'support-annotations'
     })
     compile 'com.android.support:appcompat-v7:25.1.0'
     compile 'com.android.support:design:25.1.0'
     compile 'com.android.support:multidex:1.0.1'
     testCompile 'junit:junit:4.12'
 }
 
 apply plugin: 'com.facebook.testing.screenshot'
 
```
 

Already have that there @tdrhq

**Comment by naderz** [comment]
I think your library is always overriding the instrumentation tag in the manifest.

**Comment by naderz** [comment]
who modifies customTestRunner = false ? seems its always false

**Comment by tdrhq** [comment]
(To be clear, that customTestRunner is a configurable option that you should set if you don't want to use the default runner)

**Comment by naderz** [comment]
No worries, so simply adding 

`project.screenshots.customTestRunner true`

Would work ? is that the way to configure it ?

**Comment by tdrhq** [comment]
So, let me know if you're sending over a pull request with an example :)

**Comment by naderz** [comment]
@tdrhq https://github.com/facebook/screenshot-tests-for-android/pull/52 :)
