### ISSUE TITLE
Failed to create snapshoot on view not measured

### ISSUE THREAD

**Issue by DavidBcn** [facebook/screenshot-tests-for-android#56]
could someone explain me what I am doing wrong?

```
public void test_view(){
   View view = new ImageView(getInstrumentation().getTargetContext());
   view.setBackgroundColor(Color.RED);

   ViewHelpers.setupView(view)
          .setExactWidthDp(widthDp)
          .layout();

   Screenshot.snap(view).record();
}
```

_java.lang.RuntimeException: java.lang.RuntimeException: Can't take a screenshot, since this view is not measured_

**Comment by tdrhq** [comment]
Since it's an ImageView you also need to set a Height. We use height=0 or width=0 to detect if a view is not measured (come to think of it: I should probably make this height=0 *and* width=0 and show a different error message if only one of them is zero)

**Comment by DavidBcn** [comment]
ImageView doesn't expose the width and height.
Should it work If I add layoutParams to the view with specific width and height?

**Comment by xiphirx** [comment]
You want to call `setExactHeightDp(...)` after `setExactWidthDp(...)`
