### ISSUE TITLE
Add a helpful hint about using target sdk to 22

### ISSUE THREAD

**Issue by Ankhwatcher** [facebook/screenshot-tests-for-android#58]
Can anyone point me to a fully fleshed out example of how this can be used? I've implemented everything I can find from the instructions page, this bug tracker, the wiki and the examples on the master branch and it's still not working.

Addendum: Don't you need to grant external storage permission to the app by means of a pop-up in order to write the screenshots to disk in the first place?

**Comment by tdrhq** [comment]
there are a few stand-alone examples in the examples/ directory.

As for the second part.. that might be true. I'm relying on the community telling me if there's some step I need to take to automate that. (Because technically, that issue should happen to any instrumentation test, not just screenshot tests).

I generally run this on a KitKat emulator, so I might be missing out on the extra permission stuff in M.

**Comment by trevjonez** [comment]
To work around the runtime permission issue you can set the target sdk in gradle to 22. 

I typically create a `ci` product flavor which gives me a place to put extra test only bits into the app apk. The reasoning for this is that things like app compat vector support doesn't work if you use the app context (targetContext from instrumentation registry) so having an empty activity that extends app compat activity to run these tests with can be super helpful and remain as fast as possible. This is something that needs to be in the app apk so the extra source set is super helpful to keep them out of normal builds. If your application doesn't already required external write the ci flavor manifest is a good place to add the permission as well.

That is just one option. another may be to use something like test butler https://github.com/linkedin/test-butler

**Comment by tdrhq** [comment]
Thanks @trevjonez, I've renamed the task to document this but will try it out locally before I do so

**Comment by xiphirx** [comment]
Support for API 23+ has been added with #89
