### ISSUE TITLE
Record resources displayed in a screenshot

### ISSUE THREAD

**Issue by kruton** [facebook/screenshot-tests-for-android#59]
There probably isn't even a way to do this reliably, but recording the resources displayed on the screen would be a boon for translators. There would need to be a way to tag the loading of resources (e.g., string from `strings.xml`) all the way to the `View` that it's associated with. Then this information combined with the screenshot and a snapshot of the view hierarchy it could be used to provide context images for translators.

**Comment by tdrhq** [comment]
We actually already do this to some extent from https://github.com/facebook/screenshot-tests-for-android/blob/master/core/src/main/java/com/facebook/testing/screenshot/internal/ViewHierarchy.java

It's not a fully fleshed out system, but here's a "plugin" that would dump contents of TextViews: https://github.com/facebook/screenshot-tests-for-android/blob/master/core/src/main/java/com/facebook/testing/screenshot/plugin/TextViewDumper.java . I forget if this plugin is enabled by default.

**Comment by kruton** [comment]
Interesting, reverse mapping could work as well. I'll look into that; thanks for the pointer!

**Comment by xiphirx** [comment]
Heads up, #118 changes the dump output to json rather than xml.
