### ISSUE TITLE
Bundle PIL library in jar

### ISSUE THREAD

**Issue by fangzhzh** [facebook/screenshot-tests-for-android#6]
in url here: https://facebook.github.io/screenshot-tests-for-android/#gradle-setup

It's better add an section called Pre required:
added some info 
- gradle configuation

```
screenshots {
    testApkTarget = 'packageExampleDebugAndroidTest'
    adb = '/Users/Mac/Library/Android/sdk/platform-tools/adb'
}
```
- python module 

```
pip install image
```

**Comment by andrzejtokarski** [comment]
No need to hardcode the path:
adb = android.getAdbExe().toString()

**Comment by tdrhq** [comment]
@andrzejtokarski  neat! Thanks! will make that change!

**Comment by tdrhq** [comment]
Fixed adb issue in 74ffec6e05f1d44f7d176b7232e59c536fcc84bb

For the pip install image, I'll just bundle the PIL library in the same jar. Keeping task open for this.

**Comment by fangzhzh** [comment]
@andrzejtokarski nice!

**Comment by niravnagda** [comment]
@andrzejtokarski : can you give some estimation on when this will be done?

**Comment by georgepapas** [comment]
+1

This would be a valuable enhancement.

**Comment by niravnagda** [comment]
@tdrhq @andrzejtokarski is anyone working on this?

**Comment by andrzejtokarski** [comment]
I'm not :) It was just a drive-by comment.

**Comment by tdrhq** [comment]
I tried doing this sometime back, and unfortunately it wasn't trivial since
PIL/pillow depends on native code that might be platform dependant. The
current recommendation is to still use pip-install.
