### ISSUE TITLE
Failed to create the directory for screenshots. Is your sdcard directory read-only?

### ISSUE THREAD

**Issue by FabianTerhorst** [facebook/screenshot-tests-for-android#62]
Im trying to get the plugin working on api 23+. I have already added a task to grant the required permission, but im getting "Failed to create the directory for screenshots. Is your sdcard directory read-only?" after calling 
```java
Screenshot.snap(view)
                .record();
```
Im not sure why im not able to create a new directory even when i got the correct permission.

**Comment by tdrhq** [comment]
Somebody else advised us to use target level 22 or above to avoid the permission issue with tests, let me know if that does anything.. I'll try to test this locally too

**Comment by FabianTerhorst** [comment]
When im using a 21 target for debug builds everything is working as expected.

**Comment by tdrhq** [comment]
@FabianTerhorst Thanks for the update! I'll try to see if I can plug in an advise somewhere in the output logs so people can discover this fix more easily
