### ISSUE TITLE
not able to run test if layout child uses DataBinding

### ISSUE THREAD

**Issue by chriswiesner** [facebook/screenshot-tests-for-android#64]
I have a layout which uses DataBinding and a (custom) child view which also uses databinding.

```
<layout>

	<data>

		<variable
			name="clickListener"
			type="..."/>
	</data>

...
<ImageView			
   android:onClick="@{clickListener::onAvatarClicked}"/>

<CustomView
   ... />
...
</layout
```
And tests fail with:

`Caused by: java.lang.IllegalStateException: DataBinding must be created in view's UI Thread`

even if I use an ActivityTestRule like 

```
LayoutInflater inflater = LayoutInflater.from(activityTestRule.getActivity());
View view = inflater.inflate(R.layout.mylayout, null, false);
```

it fails the same way.

it works if I remove the custom view

**Comment by tdrhq** [comment]
@chriswiesner You should use the @UiThreadTest annotation on these tests (this is part of the android testing tools).
