### ISSUE TITLE
Report format issues.

### ISSUE THREAD

**Issue by trevjonez** [facebook/screenshot-tests-for-android#65]
My images in the report always have an extra strip of space at the bottom. it looks to be about 1dp in size.

![image](https://cloud.githubusercontent.com/assets/5386503/24934273/d0c542de-1ed7-11e7-9d29-1c2f1a11e1e1.png)

The line through the graphic there does not happen when you view the report from safari but the bottom line is always shown.

given that the library preaches deterministic screenshot testing the generated report should probably be deterministic as well.

looks like there was some talk about making the tile size configurable or even do straight to disk capture. Straight to disk capture would be nice to see since it would solve this issue in as a side effect.

**Comment by tdrhq** [comment]
yeah this is a long standing CSS bug, (the images itself are fine, and if you're recording the screenshots this wouldn't matter)

Let me finally try to fix it (not a CSS guru, so I was hoping somebody will fix it for me with a pull request ;)

**Comment by tdrhq** [comment]
Fixed in https://github.com/facebook/screenshot-tests-for-android/commit/f174dfaa62af4535983d351db1d162441cb4a3b5, could you verify for me that this works? If so I'll release a new version early next week
