### ISSUE TITLE
Screenshot test failed, but report says it's passed

### ISSUE THREAD

**Issue by dhoskins** [facebook/screenshot-tests-for-android#72]
So I made my screenshot test deliberately fail to see what would happen.  In the console logs I see:

`android_screenshot_tests.recorder.VerifyError: Image /var/folders/qg/zyc5g3450190wrrcpyszxtxw0000gp/T/tmpAUKmxF/com.myapp.tests.ScreenshotTest_screenshotTest.png is not same as screenshots/com.myapp.tests.ScreenshotTest_screenshotTest.png`

However, in the generated JUnit XML and HTML reports, it says the test has passed.

`<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="com.myapp.tests.ScreenshotTest" tests="1" failures="0" errors="0" skipped="0" time="0.141" timestamp="2017-06-20T08:09:32" hostname="localhost">
  <properties>
    <property name="device" value="pixel_21(AVD) - 5.0.2" />
    <property name="flavor" value="DEVLIVE" />
    <property name="project" value="myapp" />
  </properties>
  <testcase name="screenshotTest" classname="com.myapp.tests.ScreenshotTest" time="0.138" />
</testsuite>`

Is this normal or is there an error with my configuration?

**Comment by dimorinny** [comment]
There are 2 stages on this library:
1) Creating screenshots
2) Verify this screenshots with your fixtures.

JUnit report generated in first stage during test execution. If your screenshots created without some problems, your JUnit XML report looks well.
But after that, screenshot checker run as python process, that doesn't know about gradle, JUnit or something else. When it founds difference between screenshots, it throws VerifyError exception.

This report doesn't know about checking screenshots. It only know about making test screenshots.

**Comment by rrupsing** [comment]
Seems like this would be a very useful reporting extension of this project, as most people running screenshot verification on CI would want to know when the validate stage is failing

**Comment by xiphirx** [comment]
Merging into #125
