### ISSUE TITLE
Tests failing on Firebase Test Lab

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [facebook/screenshot-tests-for-android#73]
I'm able to run and pass all the tests. On pulling the artifacts from Firebase to run `./gradlew screenshotTestsFromDirectory` (command is probably misspelled here), I always run into a manifest parse error. And an error message that `Screenshot.onDestroy()` was probably not called.

I have access to all the images. The manifest is broken though.

Is there a way to bypass the manifest? What is it used for? My only option right now is to write my own script to stitch and compare the files.

**Comment by dimorinny** [comment]
It looks like the same issue #54.
Look it my answer here.
