### ISSUE TITLE
Depend on assembleAndroidTest instead of variant-specific package task?

### ISSUE THREAD

**Issue by JakeWharton** [facebook/screenshot-tests-for-android#75]
This would allows the case where flavors exist to work out the box. It's relatively appropriate since you end up invoking the variant-agnostic `connectedAndroidTest` anyway.

**Comment by tdrhq** [comment]
@JakeWharton Not exactly a gradle expert, could you explain this a bit more? Looks like assembleAndroidTest is for creating the test apk, which means I'd still need to install and run the apk through something, right?

**Comment by JakeWharton** [comment]
Yes, but you do that already.

This change allows modules which use product flavors to work out-of-the-box instead of having to correct the task name. For example, we don't have a `packageDebugAndroidTest` task because we have `packageInternalDebugAndroidTest`. Both configurations, however, have an `assembleAndroidTest` task for the debug variants.
