### ISSUE TITLE
Corrupt image file being created

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [facebook/screenshot-tests-for-android#76]
I'm running our instrumentation tests on Firebase Test Lab and while 90% of the time, everything goes as expected, sometimes, `Image.open()` fails with an `OSError` like so:

![image](https://user-images.githubusercontent.com/26975170/28290249-8bbbd4f4-6afa-11e7-9551-0cd9de5c42e9.png)

This is because the file in question is erroneously generated as follows :

![image](https://user-images.githubusercontent.com/26975170/28290356-f7d50c50-6afa-11e7-9537-d357d68a7ca5.png)

The file size is `49B`. I'm not even sure if this is an image file as I don't get the option to `Save Image as`.

Usually, on running the test again, it fixes itself. But I'm trying to get to the root of the issue to solve it.

Do you have any idea why this could be happening?

**Comment by dimorinny** [comment]
I solve the same problem too :)

I tried to decode PNG after screenshot making and recreate screenshot if image is corrupted, but it didn't solve this problem. It means, that problem in Firebase Test Lab again :(

I think, that it is the same issue: #54 

I solved this problem by storing screenshots in application internal storage and move this data to external storage, when runner is destroyed. In this case Firebase Test Lab can't move this data from test device. You can find this changes here: https://github.com/dimorinny/screenshot-tests-for-android

I plan to create pull request with this changes on this week.

**Comment by sridhar-vadlamani-ck** [comment]
That would be awesome.

**Comment by emanzanoaxa** [comment]
Not fully related to the issue but can you give me some guide to run facebook screenshot verifyMode tests on firebase test lab from C.I? I don't know if I can run custom gradle tasks on gcloud firebase test lab.

**Comment by sridhar-vadlamani-ck** [comment]
@emanzanoaxa https://gitter.im/temp-screenshot-tests-for-android/Lobby Let's chat
